create role anon nologin; create role authenticated nologin; create role service_role nologin; create role supabase_admin nologin; create role authenticator nologin; create role supabase_auth_admin nologin; create role supabase_storage_admin nologin;
create schema auth; create schema extensions; create schema storage; create schema net; create schema cron; create schema vault;
create extension if not exists pgcrypto with schema extensions;
create extension if not exists "uuid-ossp" with schema extensions;
create extension if not exists pg_trgm with schema extensions;
create table auth.users(id uuid primary key default gen_random_uuid(), email text, raw_user_meta_data jsonb default '{}', raw_app_meta_data jsonb default '{}', created_at timestamptz default now(), email_confirmed_at timestamptz, last_sign_in_at timestamptz, is_anonymous boolean default false, deleted_at timestamptz, updated_at timestamptz, encrypted_password text, confirmation_token text, recovery_token text, email_change text, email_change_token_new text, phone text, banned_until timestamptz, confirmed_at timestamptz, is_sso_user boolean default false, aud text, role text, instance_id uuid, raw_user_meta jsonb);
create table auth.identities(id uuid primary key default gen_random_uuid(), user_id uuid, provider text, identity_data jsonb, provider_id text, email text, created_at timestamptz default now(), updated_at timestamptz, last_sign_in_at timestamptz);
create table auth.sessions(id uuid primary key default gen_random_uuid(), user_id uuid, created_at timestamptz default now());
create table auth.refresh_tokens(id bigserial primary key, user_id text, session_id uuid, revoked boolean, created_at timestamptz default now());
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub', true),'')::uuid $$;
create function auth.role() returns text language sql stable as $$ select coalesce(nullif(current_setting('request.jwt.claim.role', true),''),'anon') $$;
create function auth.jwt() returns jsonb language sql stable as $$ select coalesce(nullif(current_setting('request.jwt.claims', true),''),'{}')::jsonb $$;
create function auth.email() returns text language sql stable as $$ select null::text $$;
create table storage.objects(id uuid primary key default gen_random_uuid(), bucket_id text, name text, owner uuid, created_at timestamptz default now(), metadata jsonb);
create table storage.buckets(id text primary key, name text, public boolean);
create function net.http_post(url text, body jsonb default '{}', params jsonb default '{}', headers jsonb default '{}', timeout_milliseconds int default 1000) returns bigint language sql as $$ select 1::bigint $$;
create function cron.schedule(a text, b text, c text) returns bigint language sql as $$ select 1::bigint $$;
create function cron.unschedule(a text) returns boolean language sql as $$ select true $$;
create table vault.decrypted_secrets(name text, decrypted_secret text);
