-- Migration: Add more Polish cities to marketing_cities table

INSERT INTO marketing_cities (name) VALUES
    ('Ostrów Wielkopolski'), ('Siemianowice Śląskie'), ('Pabianice'), ('Zielona Góra'),
    ('Leszno'), ('Zamość'), ('Tarnowskie Góry'), ('Stalowa Wola'), ('Mielec'),
    ('Tarnobrzeg'), ('Suwałki'), ('Przemyśl'), ('Ełk'), ('Piaseczno'),
    ('Otwock'), ('Żory'), ('Racibórz'), ('Oświęcim'), ('Cieszyn'),
    ('Jawor'), ('Legionowo'), ('Pruszków'), ('Ostrowiec Świętokrzyski'), ('Stargard'),
    ('Gdańsk'), ('Gdynia'), ('Sopot'), ('Wejherowo'), ('Reda'), ('Rumia'),
    ('Puławy'), ('Kraśnik'), ('Biłgoraj'), ('Lubartów'), ('Łuków'),
    ('Biała Podlaska'), ('Chełm'), ('Zamość'), ('Tomaszów Lubelski'), ('Janów Lubelski'),
    ('Kutno'), ('Łowicz'), ('Skierniewice'), ('Rawa Mazowiecka'), ('Sochaczew'),
    ('Grodzisk Mazowiecki'), ('Nowy Dwór Mazowiecki'), ('Mińsk Mazowiecki'), ('Siedlce'), ('Garwolin'),
    ('Głogów'), ('Bolesławiec'), ('Lubań'), ('Zgorzelec'), ('Jelenia Góra'),
    ('Kłodzko'), ('Dzierżoniów'), ('Wałbrzych'), ('Świdnica'), ('Jawor'),
    ('Nowa Ruda'), ('Polanica-Zdrój'), ('Lwówek Śląski'), ('Bogatynia'), ('Złotoryja'),
    ('Oława'), ('Środa Śląska'), ('Trzebnica'), ('Milicz'), ('Wrocław'),
    ('Namysłów'), ('Kluczbork'), ('Opole'), ('Kędzierzyn-Koźle'), ('Nysa'),
    ('Brzeg'), ('Strzelce Opolskie'), ('Prudnik'), ('Głubczyce'), ('Krapkowice'),
    ('Głuchołazy'), ('Paczków'), ('Biała'), ('Praszka'), ('Dobrodzień'),
    ('Ząbkowice Śląskie'), ('Ziębice'), ('Bardo'), ('Kamieniec Ząbkowicki'), ('Srebrna Góra'),
    ('Kozienice'), ('Radom'), ('Pionki'), ('Szydłowiec'), ('Przysucha'),
    ('Grójec'), ('Warka'), ('Góra Kalwaria'), ('Mogielnica'), ('Białobrzegi'),
    ('Żyrardów'), ('Skierniewice'), ('Łódź'), ('Piotrków Trybunalski'), ('Tomaszów Mazowiecki'),
    ('Bełchatów'), ('Pabianice'), ('Zduńska Wola'), ('Sieradz'), ('Wieluń'),
    ('Radomsko'), ('Łask'), ('Konstantynów Łódzki'), ('Aleksandrów Łódzki'), ('Ozorków'),
    ('Kalisz'), ('Ostrów Wielkopolski'), ('Turek'), ('Konin'), ('Koło'),
    ('Słupca'), ('Pleszew'), ('Jarocin'), ('Krotoszyn'), ('Ostrzeszów'),
    ('Kępno'), ('Wieruszów'), ('Łęczyca'), ('Poddębice'), ('Łowicz'),
    ('Kutno'), ('Łęczyca'), ('Włocławek'), ('Lipno'), ('Rypin'),
    ('Brodnica'), ('Golub-Dobrzyń'), ('Toruń'), ('Chełmno'), ('Grudziądz'),
    ('Świecie'), ('Bydgoszcz'), ('Inowrocław'), ('Nakło nad Notecią'), ('Żnin'),
    ('Szubin'), ('Sępólno Krajeńskie'), ('Tuchola'), ('Chojnice'), ('Czersk'),
    ('Starogard Gdański'), ('Tczew'), ('Kwidzyn'), ('Malbork'), ('Sztum'),
    ('Gniew'), ('Pruszcz Gdański'), ('Gdańsk'), ('Sopot'), ('Gdynia'),
    ('Puck'), ('Hel'), ('Władysławowo'), ('Kartuzy'), ('Kościerzyna'),
    ('Chojnice'), ('Człuchów'), ('Lębork'), ('Bytów'), ('Słupsk'),
    ('Miastko'), ('Czarna Dąbrówka'), ('Kołobrzeg'), ('Koszalin'), ('Sławno'),
    ('Darłowo'), ('Polanów'), ('Karlino'), ('Białogard'), ('Świdwin'),
    ('Drawsko Pomorskie'), ('Czaplinek'), ('Szczecinek'), ('Barlinek'), ('Myślibórz'),
    ('Pyrzyce'), ('Chojna'), ('Gryfino'), ('Cedynia'), ('Trzcińsko-Zdrój'),
    ('Mieszkowice'), ('Kołbaskowo'), ('Police'), ('Nowe Warpno'), ('Szczecin'),
    ('Świnoujście'), ('Dziwnów'), ('Międzyzdroje'), ('Wolin'), ('Kamień Pomorski'),
    ('Goleniów'), ('Nowogard'), ('Gryfice'), ('Płoty'), ('Resko'),
    ('Łobez'), ('Węgorzyno'), ('Ińsko'), ('Stargard'), ('Dobra'),
    ('Chociwel'), ('Dobra'), ('Police'), ('Kołbaskowo'), ('Kobylanka'),
    ('Gorzów Wielkopolski'), ('Kostrzyn nad Odrą'), ('Kłodawa'), ('Rzepin'), ('Słubice'),
    ('Krosno Odrzańskie'), ('Zbąszyń'), ('Świebodzin'), ('Skwierzyna'), ('Międzyrzecz'),
    ('Bledzew'), ('Sulęcin'), ('Torzym'), ('Ośno Lubuskie'), ('Rzepin'),
    ('Cybinka'), ('Słubice'), ('Gubin'), ('Forst'), ('Bad Muskau'),
    ('Łagów'), ('Świebodzin'), ('Zbąszynek'), ('Babimost'), ('Nowa Sól'),
    ('Kożuchów'), ('Szprotawa'), ('Małomice'), ('Gożdzik'), ('Iłowa'),
    ('Przemków'), ('Chocianów'), ('Wschowa'), ('Szlichtyngowa'), ('Sława'),
    ('Kargowa'), ('Babimost'), ('Zielona Góra'), ('Czerwieńsk'), ('Sulechów'),
    ('Nowogród Bobrzański'), ('Bytom Odrzański'), ('Niegosławice'), ('Kożuchów'), ('Bojadła'),
    ('Brody'), ('Lubsko'), ('Żary'), ('Jasień'), ('Łęknica'),
    ('Gozdnica'), ('Przewóz'), ('Trzebiel'), ('Lipinki Łużyckie'), ('Olszyna'),
    ('Pieńsk'), ('Zgorzelec'), ('Bogatynia'), ('Turoszów'), ('Porajów'),
    ('Radomierz'), ('Sulików'), ('Zawidów'), ('Świeradów-Zdrój'), ('Lubań'),
    ('Gryfów Śląski'), ('Olszyna'), ('Leśna'), ('Platerówka'), ('Pieńsk'),
    ('Zgorzelec'), ('Węgliniec'), ('Węgliniec'), ('Gozdnica'), ('Przewóz'),
    ('Trzebiel'), ('Lipinki Łużyckie'), ('Olszyna'), ('Pieńsk'), ('Zgorzelec'),
    ('Bogatynia'), ('Turoszów'), ('Porajów'), ('Radomierz'), ('Sulików'),
    ('Zawidów'), ('Świeradów-Zdrój'), ('Lubań'), ('Gryfów Śląski'), ('Olszyna'),
    ('Leśna'), ('Platerówka'), ('Pieńsk'), ('Zgorzelec'), ('Węgliniec')
ON CONFLICT (name) DO NOTHING;
