-- Update population for all cities from GUS (stan na 30 czerwca 2025)
-- Major cities (top 50)
UPDATE marketing_cities SET population = 3048 WHERE name = 'Warszawa';
UPDATE marketing_cities SET population = 1635 WHERE name = 'Kraków';
UPDATE marketing_cities SET population = 1352 WHERE name = 'Wrocław';
UPDATE marketing_cities SET population = 996 WHERE name = 'Poznań';
UPDATE marketing_cities SET population = 978 WHERE name = 'Łódź';
UPDATE marketing_cities SET population = 812 WHERE name = 'Gdańsk';
UPDATE marketing_cities SET population = 600 WHERE name = 'Szczecin';
UPDATE marketing_cities SET population = 507 WHERE name = 'Lublin';
UPDATE marketing_cities SET population = 492 WHERE name = 'Bydgoszcz';
UPDATE marketing_cities SET population = 466 WHERE name = 'Katowice';
UPDATE marketing_cities SET population = 362 WHERE name = 'Gdynia';
UPDATE marketing_cities SET population = 345 WHERE name = 'Białystok';
UPDATE marketing_cities SET population = 296 WHERE name = 'Toruń';
UPDATE marketing_cities SET population = 280 WHERE name = 'Częstochowa';
UPDATE marketing_cities SET population = 267 WHERE name = 'Radom';
UPDATE marketing_cities SET population = 265 WHERE name = 'Rzeszów';
UPDATE marketing_cities SET population = 259 WHERE name = 'Gliwice';
UPDATE marketing_cities SET population = 254 WHERE name = 'Olsztyn';
UPDATE marketing_cities SET population = 232 WHERE name = 'Sosnowiec';
UPDATE marketing_cities SET population = 226 WHERE name = 'Bielsko-Biała';
UPDATE marketing_cities SET population = 225 WHERE name = 'Zabrze';
UPDATE marketing_cities SET population = 217 WHERE name = 'Kielce';
UPDATE marketing_cities SET population = 212 WHERE name = 'Gorzów Wielkopolski';
UPDATE marketing_cities SET population = 207 WHERE name = 'Rybnik';
UPDATE marketing_cities SET population = 200 WHERE name = 'Bytom';
UPDATE marketing_cities SET population = 177 WHERE name = 'Ruda Śląska';
UPDATE marketing_cities SET population = 169 WHERE name = 'Zielona Góra';
UPDATE marketing_cities SET population = 168 WHERE name = 'Tychy';
UPDATE marketing_cities SET population = 151 WHERE name = 'Chorzów';
UPDATE marketing_cities SET population = 146 WHERE name = 'Opole';
UPDATE marketing_cities SET population = 139 WHERE name = 'Elbląg';
UPDATE marketing_cities SET population = 133 WHERE name = 'Grudziądz';
UPDATE marketing_cities SET population = 131 WHERE name = 'Legnica';
UPDATE marketing_cities SET population = 131 WHERE name = 'Płock';
UPDATE marketing_cities SET population = 130 WHERE name = 'Kalisz';
UPDATE marketing_cities SET population = 129 WHERE name = 'Słupsk';
UPDATE marketing_cities SET population = 128 WHERE name = 'Koszalin';
UPDATE marketing_cities SET population = 121 WHERE name = 'Pruszków';
UPDATE marketing_cities SET population = 114 WHERE name = 'Dąbrowa Górnicza';
UPDATE marketing_cities SET population = 113 WHERE name = 'Włocławek';
UPDATE marketing_cities SET population = 113 WHERE name = 'Jastrzębie-Zdrój';
UPDATE marketing_cities SET population = 113 WHERE name = 'Mysłowice';
UPDATE marketing_cities SET population = 111 WHERE name = 'Wałbrzych';
UPDATE marketing_cities SET population = 105 WHERE name = 'Tarnów';
UPDATE marketing_cities SET population = 104 WHERE name = 'Stargard';
UPDATE marketing_cities SET population = 103 WHERE name = 'Głogów';
UPDATE marketing_cities SET population = 103 WHERE name = 'Rumia';
UPDATE marketing_cities SET population = 96 WHERE name = 'Piła';
UPDATE marketing_cities SET population = 94 WHERE name = 'Nowy Sącz';
UPDATE marketing_cities SET population = 94 WHERE name = 'Jaworzno';
UPDATE marketing_cities SET population = 92 WHERE name = 'Leszno';
UPDATE marketing_cities SET population = 90 WHERE name = 'Lubin';
UPDATE marketing_cities SET population = 89 WHERE name = 'Żory';
UPDATE marketing_cities SET population = 88 WHERE name = 'Siemianowice Śląskie';
UPDATE marketing_cities SET population = 88 WHERE name = 'Gniezno';
UPDATE marketing_cities SET population = 85 WHERE name = 'Siedlce';
UPDATE marketing_cities SET population = 84 WHERE name = 'Jelenia Góra';
UPDATE marketing_cities SET population = 84 WHERE name = 'Inowrocław';
UPDATE marketing_cities SET population = 84 WHERE name = 'Tarnowskie Góry';
UPDATE marketing_cities SET population = 83 WHERE name = 'Pabianice';
UPDATE marketing_cities SET population = 83 WHERE name = 'Ełk';
UPDATE marketing_cities SET population = 82 WHERE name = 'Piotrków Trybunalski';
UPDATE marketing_cities SET population = 82 WHERE name = 'Piaseczno';
UPDATE marketing_cities SET population = 77 WHERE name = 'Świętochłowice';
UPDATE marketing_cities SET population = 77 WHERE name = 'Ostrów Wielkopolski';
UPDATE marketing_cities SET population = 76 WHERE name = 'Suwałki';
UPDATE marketing_cities SET population = 74 WHERE name = 'Ząbki';
UPDATE marketing_cities SET population = 73 WHERE name = 'Zgierz';
UPDATE marketing_cities SET population = 72 WHERE name = 'Tomaszów Mazowiecki';
UPDATE marketing_cities SET population = 72 WHERE name = 'Kędzierzyn-Koźle';
UPDATE marketing_cities SET population = 72 WHERE name = 'Piekary Śląskie';
UPDATE marketing_cities SET population = 71 WHERE name = 'Łomża';
UPDATE marketing_cities SET population = 70 WHERE name = 'Przemyśl';
UPDATE marketing_cities SET population = 69 WHERE name = 'Konin';
UPDATE marketing_cities SET population = 67 WHERE name = 'Skierniewice';
UPDATE marketing_cities SET population = 67 WHERE name = 'Legionowo';
UPDATE marketing_cities SET population = 66 WHERE name = 'Racibórz';
UPDATE marketing_cities SET population = 63 WHERE name = 'Świdnica';
UPDATE marketing_cities SET population = 63 WHERE name = 'Marki';
UPDATE marketing_cities SET population = 63 WHERE name = 'Tczew';
UPDATE marketing_cities SET population = 63 WHERE name = 'Reda';
UPDATE marketing_cities SET population = 63 WHERE name = 'Świnoujście';
UPDATE marketing_cities SET population = 62 WHERE name = 'Zamość';
UPDATE marketing_cities SET population = 62 WHERE name = 'Chojnice';
UPDATE marketing_cities SET population = 62 WHERE name = 'Wodzisław Śląski';
UPDATE marketing_cities SET population = 61 WHERE name = 'Nowy Dwór Mazowiecki';
UPDATE marketing_cities SET population = 61 WHERE name = 'Ostrowiec Świętokrzyski';
UPDATE marketing_cities SET population = 60 WHERE name = 'Oława';
UPDATE marketing_cities SET population = 59 WHERE name = 'Mielec';
UPDATE marketing_cities SET population = 58 WHERE name = 'Bolesławiec';
UPDATE marketing_cities SET population = 58 WHERE name = 'Chełm';
UPDATE marketing_cities SET population = 57 WHERE name = 'Biała Podlaska';
UPDATE marketing_cities SET population = 56 WHERE name = 'Oświęcim';
UPDATE marketing_cities SET population = 56 WHERE name = 'Wołomin';
UPDATE marketing_cities SET population = 56 WHERE name = 'Kołobrzeg';
UPDATE marketing_cities SET population = 55 WHERE name = 'Mikołów';
UPDATE marketing_cities SET population = 54 WHERE name = 'Otwock';
UPDATE marketing_cities SET population = 52 WHERE name = 'Mińsk Mazowiecki';
UPDATE marketing_cities SET population = 52 WHERE name = 'Kobyłka';
UPDATE marketing_cities SET population = 52 WHERE name = 'Dębica';
UPDATE marketing_cities SET population = 51 WHERE name = 'Żary';
UPDATE marketing_cities SET population = 51 WHERE name = 'Starogard Gdański';
UPDATE marketing_cities SET population = 51 WHERE name = 'Wejherowo';
UPDATE marketing_cities SET population = 51 WHERE name = 'Będzin';
UPDATE marketing_cities SET population = 50 WHERE name = 'Nowa Sól';
UPDATE marketing_cities SET population = 50 WHERE name = 'Bełchatów';
UPDATE marketing_cities SET population = 50 WHERE name = 'Kutno';
UPDATE marketing_cities SET population = 49 WHERE name = 'Sochaczew';
UPDATE marketing_cities SET population = 49 WHERE name = 'Żyrardów';
UPDATE marketing_cities SET population = 49 WHERE name = 'Cieszyn';
UPDATE marketing_cities SET population = 49 WHERE name = 'Knurów';
UPDATE marketing_cities SET population = 49 WHERE name = 'Luboń';
UPDATE marketing_cities SET population = 48 WHERE name = 'Radomsko';
UPDATE marketing_cities SET population = 48 WHERE name = 'Brzeg';
UPDATE marketing_cities SET population = 48 WHERE name = 'Pruszcz Gdański';
UPDATE marketing_cities SET population = 48 WHERE name = 'Czechowice-Dziedzice';
UPDATE marketing_cities SET population = 48 WHERE name = 'Środa Wielkopolska';
UPDATE marketing_cities SET population = 47 WHERE name = 'Puławy';
UPDATE marketing_cities SET population = 47 WHERE name = 'Bochnia';
UPDATE marketing_cities SET population = 47 WHERE name = 'Ciechanów';
UPDATE marketing_cities SET population = 47 WHERE name = 'Ostrołęka';
UPDATE marketing_cities SET population = 47 WHERE name = 'Giżycko';
UPDATE marketing_cities SET population = 46 WHERE name = 'Chrzanów';
UPDATE marketing_cities SET population = 45 WHERE name = 'Grodzisk Mazowiecki';
UPDATE marketing_cities SET population = 45 WHERE name = 'Pszczyna';
UPDATE marketing_cities SET population = 44 WHERE name = 'Nowy Targ';
UPDATE marketing_cities SET population = 44 WHERE name = 'Malbork';
UPDATE marketing_cities SET population = 44 WHERE name = 'Szczecinek';
UPDATE marketing_cities SET population = 42 WHERE name = 'Oleśnica';
UPDATE marketing_cities SET population = 42 WHERE name = 'Świdnik';
UPDATE marketing_cities SET population = 42 WHERE name = 'Sieradz';
UPDATE marketing_cities SET population = 42 WHERE name = 'Lębork';
UPDATE marketing_cities SET population = 41 WHERE name = 'Jarosław';
UPDATE marketing_cities SET population = 41 WHERE name = 'Czeladź';
UPDATE marketing_cities SET population = 41 WHERE name = 'Starachowice';
UPDATE marketing_cities SET population = 40 WHERE name = 'Brodnica';
UPDATE marketing_cities SET population = 40 WHERE name = 'Wieliczka';
UPDATE marketing_cities SET population = 40 WHERE name = 'Zawiercie';
UPDATE marketing_cities SET population = 39 WHERE name = 'Kwidzyn';
UPDATE marketing_cities SET population = 39 WHERE name = 'Sopot';
UPDATE marketing_cities SET population = 39 WHERE name = 'Swarzędz';
UPDATE marketing_cities SET population = 39 WHERE name = 'Wągrowiec';
UPDATE marketing_cities SET population = 38 WHERE name = 'Ożarów Mazowiecki';
UPDATE marketing_cities SET population = 38 WHERE name = 'Stalowa Wola';
UPDATE marketing_cities SET population = 38 WHERE name = 'Skarżysko-Kamienna';
UPDATE marketing_cities SET population = 38 WHERE name = 'Police';
UPDATE marketing_cities SET population = 37 WHERE name = 'Zgorzelec';
UPDATE marketing_cities SET population = 37 WHERE name = 'Żagań';
UPDATE marketing_cities SET population = 37 WHERE name = 'Nysa';
UPDATE marketing_cities SET population = 37 WHERE name = 'Tarnobrzeg';
UPDATE marketing_cities SET population = 37 WHERE name = 'Lubliniec';
UPDATE marketing_cities SET population = 37 WHERE name = 'Iława';
UPDATE marketing_cities SET population = 36 WHERE name = 'Polkowice';
UPDATE marketing_cities SET population = 36 WHERE name = 'Krosno';
UPDATE marketing_cities SET population = 35 WHERE name = 'Zduńska Wola';
UPDATE marketing_cities SET population = 35 WHERE name = 'Mława';
UPDATE marketing_cities SET population = 35 WHERE name = 'Ostróda';
UPDATE marketing_cities SET population = 34 WHERE name = 'Świebodzin';
UPDATE marketing_cities SET population = 34 WHERE name = 'Gryfino';
UPDATE marketing_cities SET population = 34 WHERE name = 'Wałcz';
UPDATE marketing_cities SET population = 33 WHERE name = 'Konstantynów Łódzki';
UPDATE marketing_cities SET population = 33 WHERE name = 'Wyszków';
UPDATE marketing_cities SET population = 33 WHERE name = 'Rydułtowy';
UPDATE marketing_cities SET population = 33 WHERE name = 'Krotoszyn';
UPDATE marketing_cities SET population = 33 WHERE name = 'Września';
UPDATE marketing_cities SET population = 32 WHERE name = 'Bielawa';
UPDATE marketing_cities SET population = 32 WHERE name = 'Kościan';
UPDATE marketing_cities SET population = 32 WHERE name = 'Goleniów';
UPDATE marketing_cities SET population = 31 WHERE name = 'Łowicz';
UPDATE marketing_cities SET population = 31 WHERE name = 'Grójec';
UPDATE marketing_cities SET population = 31 WHERE name = 'Ostrów Mazowiecka';
UPDATE marketing_cities SET population = 31 WHERE name = 'Brwinów';
UPDATE marketing_cities SET population = 31 WHERE name = 'Jasło';
UPDATE marketing_cities SET population = 31 WHERE name = 'Żywiec';
UPDATE marketing_cities SET population = 30 WHERE name = 'Świecie';
UPDATE marketing_cities SET population = 30 WHERE name = 'Sulechów';
UPDATE marketing_cities SET population = 30 WHERE name = 'Płońsk';
UPDATE marketing_cities SET population = 30 WHERE name = 'Piastów';
UPDATE marketing_cities SET population = 30 WHERE name = 'Myszków';
UPDATE marketing_cities SET population = 30 WHERE name = 'Szczytno';
UPDATE marketing_cities SET population = 29 WHERE name = 'Olkusz';
UPDATE marketing_cities SET population = 29 WHERE name = 'Sulejówek';
UPDATE marketing_cities SET population = 29 WHERE name = 'Bytów';
UPDATE marketing_cities SET population = 29 WHERE name = 'Czerwionka-Leszczyny';
UPDATE marketing_cities SET population = 28 WHERE name = 'Garwolin';
UPDATE marketing_cities SET population = 28 WHERE name = 'Pisz';
UPDATE marketing_cities SET population = 28 WHERE name = 'Oborniki';
UPDATE marketing_cities SET population = 27 WHERE name = 'Świebodzice';
UPDATE marketing_cities SET population = 27 WHERE name = 'Siechnice';
UPDATE marketing_cities SET population = 27 WHERE name = 'Kartuzy';
UPDATE marketing_cities SET population = 27 WHERE name = 'Nowogard';
UPDATE marketing_cities SET population = 26 WHERE name = 'Łuków';
UPDATE marketing_cities SET population = 26 WHERE name = 'Słubice';
UPDATE marketing_cities SET population = 26 WHERE name = 'Rawa Mazowiecka';
UPDATE marketing_cities SET population = 26 WHERE name = 'Ozorków';
UPDATE marketing_cities SET population = 26 WHERE name = 'Niepołomice';
UPDATE marketing_cities SET population = 26 WHERE name = 'Bielsk Podlaski';
UPDATE marketing_cities SET population = 26 WHERE name = 'Kętrzyn';
UPDATE marketing_cities SET population = 26 WHERE name = 'Rawicz';
UPDATE marketing_cities SET population = 26 WHERE name = 'Szamotuły';
UPDATE marketing_cities SET population = 26 WHERE name = 'Śrem';
UPDATE marketing_cities SET population = 25 WHERE name = 'Lubań';
UPDATE marketing_cities SET population = 25 WHERE name = 'Międzyrzec Podlaski';
UPDATE marketing_cities SET population = 25 WHERE name = 'Józefów';
UPDATE marketing_cities SET population = 25 WHERE name = 'Lędziny';
UPDATE marketing_cities SET population = 25 WHERE name = 'Jarocin';
UPDATE marketing_cities SET population = 24 WHERE name = 'Kłodzko';
UPDATE marketing_cities SET population = 24 WHERE name = 'Wieluń';
UPDATE marketing_cities SET population = 24 WHERE name = 'Trzebinia';
UPDATE marketing_cities SET population = 24 WHERE name = 'Przasnysz';
UPDATE marketing_cities SET population = 24 WHERE name = 'Radzymin';
UPDATE marketing_cities SET population = 24 WHERE name = 'Kluczbork';
UPDATE marketing_cities SET population = 24 WHERE name = 'Namysłów';
UPDATE marketing_cities SET population = 24 WHERE name = 'Augustów';
UPDATE marketing_cities SET population = 24 WHERE name = 'Zambrów';
UPDATE marketing_cities SET population = 24 WHERE name = 'Łaziska Górne';
UPDATE marketing_cities SET population = 24 WHERE name = 'Turek';
UPDATE marketing_cities SET population = 23 WHERE name = 'Kraśnik';
UPDATE marketing_cities SET population = 23 WHERE name = 'Kostrzyn nad Odrą';
UPDATE marketing_cities SET population = 23 WHERE name = 'Wschowa';
UPDATE marketing_cities SET population = 23 WHERE name = 'Skawina';
UPDATE marketing_cities SET population = 23 WHERE name = 'Zakopane';
UPDATE marketing_cities SET population = 23 WHERE name = 'Sanok';
UPDATE marketing_cities SET population = 23 WHERE name = 'Orzesze';
UPDATE marketing_cities SET population = 23 WHERE name = 'Bieruń';
UPDATE marketing_cities SET population = 23 WHERE name = 'Radlin';
UPDATE marketing_cities SET population = 23 WHERE name = 'Działdowo';
UPDATE marketing_cities SET population = 23 WHERE name = 'Mrągowo';
UPDATE marketing_cities SET population = 23 WHERE name = 'Nowy Tomyśl';
UPDATE marketing_cities SET population = 23 WHERE name = 'Pleszew';
UPDATE marketing_cities SET population = 23 WHERE name = 'Świdwin';
UPDATE marketing_cities SET population = 22 WHERE name = 'Jelcz-Laskowice';
UPDATE marketing_cities SET population = 22 WHERE name = 'Aleksandrów Łódzki';
UPDATE marketing_cities SET population = 22 WHERE name = 'Lubiąż';
UPDATE marketing_cities SET population = 22 WHERE name = 'Konstancin-Jeziorna';
UPDATE marketing_cities SET population = 22 WHERE name = 'Sokołów Podlaski';
UPDATE marketing_cities SET population = 22 WHERE name = 'Łomianki';
UPDATE marketing_cities SET population = 22 WHERE name = 'Grajewo';
UPDATE marketing_cities SET population = 22 WHERE name = 'Grodzisk Wielkopolski';
UPDATE marketing_cities SET population = 22 WHERE name = 'Pobiedziska';
UPDATE marketing_cities SET population = 22 WHERE name = 'Choszczno';
UPDATE marketing_cities SET population = 21 WHERE name = 'Lipno';
UPDATE marketing_cities SET population = 21 WHERE name = 'Biłgoraj';
UPDATE marketing_cities SET population = 21 WHERE name = 'Międzyrzecz';
UPDATE marketing_cities SET population = 21 WHERE name = 'Brzesko';
UPDATE marketing_cities SET population = 21 WHERE name = 'Pułtusk';
UPDATE marketing_cities SET population = 21 WHERE name = 'Zielonka';
UPDATE marketing_cities SET population = 21 WHERE name = 'Kościerzyna';
UPDATE marketing_cities SET population = 21 WHERE name = 'Skoczów';
UPDATE marketing_cities SET population = 21 WHERE name = 'Bartoszyce';
UPDATE marketing_cities SET population = 21 WHERE name = 'Nidzica';
UPDATE marketing_cities SET population = 21 WHERE name = 'Chodzież';
UPDATE marketing_cities SET population = 21 WHERE name = 'Murowana Goślina';
UPDATE marketing_cities SET population = 20 WHERE name = 'Jawor';
UPDATE marketing_cities SET population = 20 WHERE name = 'Trzebnica';
UPDATE marketing_cities SET population = 20 WHERE name = 'Opoczno';
UPDATE marketing_cities SET population = 20 WHERE name = 'Andrychów';
UPDATE marketing_cities SET population = 20 WHERE name = 'Milanówek';
UPDATE marketing_cities SET population = 20 WHERE name = 'Pionki';
UPDATE marketing_cities SET population = 20 WHERE name = 'Krapkowice';
UPDATE marketing_cities SET population = 20 WHERE name = 'Głogów Małopolski';
UPDATE marketing_cities SET population = 20 WHERE name = 'Ustroń';
UPDATE marketing_cities SET population = 20 WHERE name = 'Kępno';
UPDATE marketing_cities SET population = 19 WHERE name = 'Wąbrzeźno';
UPDATE marketing_cities SET population = 19 WHERE name = 'Limanowa';
UPDATE marketing_cities SET population = 19 WHERE name = 'Kęty';
UPDATE marketing_cities SET population = 19 WHERE name = 'Sierpc';
UPDATE marketing_cities SET population = 19 WHERE name = 'Siemiatycze';
UPDATE marketing_cities SET population = 19 WHERE name = 'Pyskowice';
UPDATE marketing_cities SET population = 19 WHERE name = 'Radzionków';
UPDATE marketing_cities SET population = 19 WHERE name = 'Sandomierz';
UPDATE marketing_cities SET population = 19 WHERE name = 'Gostyń';
UPDATE marketing_cities SET population = 19 WHERE name = 'Złotów';
UPDATE marketing_cities SET population = 18 WHERE name = 'Dzierżoniów';
UPDATE marketing_cities SET population = 18 WHERE name = 'Bogatynia';
UPDATE marketing_cities SET population = 18 WHERE name = 'Łask';
UPDATE marketing_cities SET population = 18 WHERE name = 'Wieruszów';
UPDATE marketing_cities SET population = 18 WHERE name = 'Brzeszcze';
UPDATE marketing_cities SET population = 18 WHERE name = 'Wadowice';
UPDATE marketing_cities SET population = 18 WHERE name = 'Błonie';
UPDATE marketing_cities SET population = 18 WHERE name = 'Wysokie Mazowieckie';
UPDATE marketing_cities SET population = 18 WHERE name = 'Pszów';
UPDATE marketing_cities SET population = 18 WHERE name = 'Braniewo';
UPDATE marketing_cities SET population = 18 WHERE name = 'Pasłęk';
UPDATE marketing_cities SET population = 17 WHERE name = 'Kamienna Góra';
UPDATE marketing_cities SET population = 17 WHERE name = 'Nowa Ruda';
UPDATE marketing_cities SET population = 17 WHERE name = 'Środa Śląska';
UPDATE marketing_cities SET population = 17 WHERE name = 'Strzegom';
UPDATE marketing_cities SET population = 17 WHERE name = 'Solec Kujawski';
UPDATE marketing_cities SET population = 17 WHERE name = 'Nakło nad Notecią';
UPDATE marketing_cities SET population = 17 WHERE name = 'Gorlice';
UPDATE marketing_cities SET population = 17 WHERE name = 'Myślenice';
UPDATE marketing_cities SET population = 17 WHERE name = 'Blachownia';
UPDATE marketing_cities SET population = 17 WHERE name = 'Opalenica';
UPDATE marketing_cities SET population = 17 WHERE name = 'Mosina';
UPDATE marketing_cities SET population = 17 WHERE name = 'Darłowo';
UPDATE marketing_cities SET population = 17 WHERE name = 'Sławno';
UPDATE marketing_cities SET population = 16 WHERE name = 'Kąty Wrocławskie';
UPDATE marketing_cities SET population = 16 WHERE name = 'Chełmno';
UPDATE marketing_cities SET population = 16 WHERE name = 'Szubin';
UPDATE marketing_cities SET population = 16 WHERE name = 'Żnin';
UPDATE marketing_cities SET population = 16 WHERE name = 'Janów Lubelski';
UPDATE marketing_cities SET population = 16 WHERE name = 'Lubartów';
UPDATE marketing_cities SET population = 16 WHERE name = 'Łęczna';
UPDATE marketing_cities SET population = 16 WHERE name = 'Gostynin';
UPDATE marketing_cities SET population = 16 WHERE name = 'Nasielsk';
UPDATE marketing_cities SET population = 16 WHERE name = 'Góra Kalwaria';
UPDATE marketing_cities SET population = 16 WHERE name = 'Przeworsk';
UPDATE marketing_cities SET population = 16 WHERE name = 'Ustka';
UPDATE marketing_cities SET population = 16 WHERE name = 'Gołdap';
UPDATE marketing_cities SET population = 16 WHERE name = 'Wronki';
UPDATE marketing_cities SET population = 15 WHERE name = 'Sobótka';
UPDATE marketing_cities SET population = 15 WHERE name = 'Opole Lubelskie';
UPDATE marketing_cities SET population = 15 WHERE name = 'Radzyń Podlaski';
UPDATE marketing_cities SET population = 15 WHERE name = 'Dęblin';
UPDATE marketing_cities SET population = 15 WHERE name = 'Gubin';
UPDATE marketing_cities SET population = 15 WHERE name = 'Głowno';
UPDATE marketing_cities SET population = 15 WHERE name = 'Prudnik';
UPDATE marketing_cities SET population = 15 WHERE name = 'Prabuty';
UPDATE marketing_cities SET population = 15 WHERE name = 'Białogard';
UPDATE marketing_cities SET population = 15 WHERE name = 'Kamień Pomorski';
UPDATE marketing_cities SET population = 14 WHERE name = 'Brzeg Dolny';
UPDATE marketing_cities SET population = 14 WHERE name = 'Pieńsk';
UPDATE marketing_cities SET population = 14 WHERE name = 'Złotoryja';
UPDATE marketing_cities SET population = 14 WHERE name = 'Koronowo';
UPDATE marketing_cities SET population = 14 WHERE name = 'Golub-Dobrzyń';
UPDATE marketing_cities SET population = 14 WHERE name = 'Krasnystaw';
UPDATE marketing_cities SET population = 14 WHERE name = 'Rabka-Zdrój';
UPDATE marketing_cities SET population = 14 WHERE name = 'Strzelce Opolskie';
UPDATE marketing_cities SET population = 14 WHERE name = 'Ropczyce';
UPDATE marketing_cities SET population = 14 WHERE name = 'Wasilków';
UPDATE marketing_cities SET population = 14 WHERE name = 'Sokółka';
UPDATE marketing_cities SET population = 14 WHERE name = 'Jędrzejów';
UPDATE marketing_cities SET population = 14 WHERE name = 'Lubawa';
UPDATE marketing_cities SET population = 14 WHERE name = 'Nowe Miasto Lubawskie';
UPDATE marketing_cities SET population = 14 WHERE name = 'Dobre Miasto';
UPDATE marketing_cities SET population = 14 WHERE name = 'Koło';
UPDATE marketing_cities SET population = 14 WHERE name = 'Kostrzyn';
UPDATE marketing_cities SET population = 14 WHERE name = 'Drawsko Pomorskie';
UPDATE marketing_cities SET population = 13 WHERE name = 'Strzelin';
UPDATE marketing_cities SET population = 13 WHERE name = 'Aleksandrów Kujawski';
UPDATE marketing_cities SET population = 13 WHERE name = 'Terespol';
UPDATE marketing_cities SET population = 13 WHERE name = 'Włodawa';
UPDATE marketing_cities SET population = 13 WHERE name = 'Krosno Odrzańskie';
UPDATE marketing_cities SET population = 13 WHERE name = 'Mszana Dolna';
UPDATE marketing_cities SET population = 13 WHERE name = 'Miechów';
UPDATE marketing_cities SET population = 13 WHERE name = 'Stary Sącz';
UPDATE marketing_cities SET population = 13 WHERE name = 'Bukowno';
UPDATE marketing_cities SET population = 13 WHERE name = 'Węgrów';
UPDATE marketing_cities SET population = 13 WHERE name = 'Głubczyce';
UPDATE marketing_cities SET population = 13 WHERE name = 'Łańcut';
UPDATE marketing_cities SET population = 13 WHERE name = 'Strzyżów';
UPDATE marketing_cities SET population = 13 WHERE name = 'Człuchów';
UPDATE marketing_cities SET population = 13 WHERE name = 'Skarszewy';
UPDATE marketing_cities SET population = 13 WHERE name = 'Kłobuck';
UPDATE marketing_cities SET population = 13 WHERE name = 'Końskie';
UPDATE marketing_cities SET population = 13 WHERE name = 'Morąg';
UPDATE marketing_cities SET population = 13 WHERE name = 'Węgorzewo';
UPDATE marketing_cities SET population = 13 WHERE name = 'Trzcianka';
UPDATE marketing_cities SET population = 13 WHERE name = 'Puszczykowo';
UPDATE marketing_cities SET population = 13 WHERE name = 'Wolsztyn';
UPDATE marketing_cities SET population = 12 WHERE name = 'Milicz';
UPDATE marketing_cities SET population = 12 WHERE name = 'Wołów';
UPDATE marketing_cities SET population = 12 WHERE name = 'Ciechocinek';
UPDATE marketing_cities SET population = 12 WHERE name = 'Rypin';
UPDATE marketing_cities SET population = 12 WHERE name = 'Kożuchów';
UPDATE marketing_cities SET population = 12 WHERE name = 'Strzelce Krajeńskie';
UPDATE marketing_cities SET population = 12 WHERE name = 'Sulęcin';
UPDATE marketing_cities SET population = 12 WHERE name = 'Dąbrowa Tarnowska';
UPDATE marketing_cities SET population = 12 WHERE name = 'Warka';
UPDATE marketing_cities SET population = 12 WHERE name = 'Kozienice';
UPDATE marketing_cities SET population = 12 WHERE name = 'Szydłowiec';
UPDATE marketing_cities SET population = 12 WHERE name = 'Kolbuszowa';
UPDATE marketing_cities SET population = 12 WHERE name = 'Sędziszów Małopolski';
UPDATE marketing_cities SET population = 12 WHERE name = 'Żukowo';
UPDATE marketing_cities SET population = 12 WHERE name = 'Władysławowo';
UPDATE marketing_cities SET population = 12 WHERE name = 'Kuźnia Raciborska';
UPDATE marketing_cities SET population = 12 WHERE name = 'Imielin';
UPDATE marketing_cities SET population = 12 WHERE name = 'Pińczów';
UPDATE marketing_cities SET population = 12 WHERE name = 'Barczewo';
UPDATE marketing_cities SET population = 12 WHERE name = 'Międzychód';
UPDATE marketing_cities SET population = 12 WHERE name = 'Ostrzeszów';
UPDATE marketing_cities SET population = 12 WHERE name = 'Nekla';
UPDATE marketing_cities SET population = 12 WHERE name = 'Dębno';
UPDATE marketing_cities SET population = 11 WHERE name = 'Pieszyce';
UPDATE marketing_cities SET population = 11 WHERE name = 'Boguszów-Gorce';
UPDATE marketing_cities SET population = 11 WHERE name = 'Mogilno';
UPDATE marketing_cities SET population = 11 WHERE name = 'Lubsko';
UPDATE marketing_cities SET population = 11 WHERE name = 'Brzeziny';
UPDATE marketing_cities SET population = 11 WHERE name = 'Jordanów';
UPDATE marketing_cities SET population = 11 WHERE name = 'Łaskarzew';
UPDATE marketing_cities SET population = 11 WHERE name = 'Przysucha';
UPDATE marketing_cities SET population = 11 WHERE name = 'Żuromin';
UPDATE marketing_cities SET population = 11 WHERE name = 'Mszczonów';
UPDATE marketing_cities SET population = 11 WHERE name = 'Łapy';
UPDATE marketing_cities SET population = 11 WHERE name = 'Mońki';
UPDATE marketing_cities SET population = 11 WHERE name = 'Debrzno';
UPDATE marketing_cities SET population = 11 WHERE name = 'Pelplin';
UPDATE marketing_cities SET population = 11 WHERE name = 'Sztum';
UPDATE marketing_cities SET population = 11 WHERE name = 'Wojkowice';
UPDATE marketing_cities SET population = 11 WHERE name = 'Siewierz';
UPDATE marketing_cities SET population = 11 WHERE name = 'Orneta';
UPDATE marketing_cities SET population = 11 WHERE name = 'Czarnków';
UPDATE marketing_cities SET population = 11 WHERE name = 'Rogoźno';
UPDATE marketing_cities SET population = 11 WHERE name = 'Trzebiatów';
UPDATE marketing_cities SET population = 11 WHERE name = 'Sianów';
UPDATE marketing_cities SET population = 10 WHERE name = 'Bolków';
UPDATE marketing_cities SET population = 10 WHERE name = 'Chojnów';
UPDATE marketing_cities SET population = 10 WHERE name = 'Jaworzyna Śląska';
UPDATE marketing_cities SET population = 10 WHERE name = 'Tuchola';
UPDATE marketing_cities SET population = 10 WHERE name = 'Tomaszów Lubelski';
UPDATE marketing_cities SET population = 10 WHERE name = 'Skwierzyna';
UPDATE marketing_cities SET population = 10 WHERE name = 'Sulejów';
UPDATE marketing_cities SET population = 10 WHERE name = 'Sucha Beskidzka';
UPDATE marketing_cities SET population = 10 WHERE name = 'Łochów';
UPDATE marketing_cities SET population = 10 WHERE name = 'Głuchołazy';
UPDATE marketing_cities SET population = 10 WHERE name = 'Jedlicze';
UPDATE marketing_cities SET population = 10 WHERE name = 'Nowa Dęba';
UPDATE marketing_cities SET population = 10 WHERE name = 'Hajnówka';
UPDATE marketing_cities SET population = 10 WHERE name = 'Czersk';
UPDATE marketing_cities SET population = 10 WHERE name = 'Puck';
UPDATE marketing_cities SET population = 10 WHERE name = 'Krzepice';
UPDATE marketing_cities SET population = 10 WHERE name = 'Busko-Zdrój';
UPDATE marketing_cities SET population = 10 WHERE name = 'Śmigiel';
UPDATE marketing_cities SET population = 10 WHERE name = 'Gryfice';
UPDATE marketing_cities SET population = 10 WHERE name = 'Myślibórz';
UPDATE marketing_cities SET population = 10 WHERE name = 'Pyrzyce';
UPDATE marketing_cities SET population = 9 WHERE name = 'Kudowa-Zdrój';
UPDATE marketing_cities SET population = 9 WHERE name = 'Bystrzyca Kłodzka';
UPDATE marketing_cities SET population = 9 WHERE name = 'Syców';
UPDATE marketing_cities SET population = 9 WHERE name = 'Oborniki Śląskie';
UPDATE marketing_cities SET population = 9 WHERE name = 'Żmigród';
UPDATE marketing_cities SET population = 9 WHERE name = 'Szczawno-Zdrój';
UPDATE marketing_cities SET population = 9 WHERE name = 'Sępólno Krajeńskie';
UPDATE marketing_cities SET population = 9 WHERE name = 'Barcin';
UPDATE marketing_cities SET population = 9 WHERE name = 'Hrubieszów';
UPDATE marketing_cities SET population = 9 WHERE name = 'Bychawa';
UPDATE marketing_cities SET population = 9 WHERE name = 'Tuszyn';
UPDATE marketing_cities SET population = 9 WHERE name = 'Krynica-Zdrój';
UPDATE marketing_cities SET population = 9 WHERE name = 'Białobrzegi';
UPDATE marketing_cities SET population = 9 WHERE name = 'Serock';
UPDATE marketing_cities SET population = 9 WHERE name = 'Karczew';
UPDATE marketing_cities SET population = 9 WHERE name = 'Lewin Brzeski';
UPDATE marketing_cities SET population = 9 WHERE name = 'Olesno';
UPDATE marketing_cities SET population = 9 WHERE name = 'Ozimek';
UPDATE marketing_cities SET population = 9 WHERE name = 'Brzozów';
UPDATE marketing_cities SET population = 9 WHERE name = 'Nisko';
UPDATE marketing_cities SET population = 9 WHERE name = 'Nowy Dwór Gdański';
UPDATE marketing_cities SET population = 9 WHERE name = 'Wisła';
UPDATE marketing_cities SET population = 9 WHERE name = 'Miasteczko Śląskie';
UPDATE marketing_cities SET population = 9 WHERE name = 'Chmielnik';
UPDATE marketing_cities SET population = 9 WHERE name = 'Lidzbark Warmiński';
UPDATE marketing_cities SET population = 9 WHERE name = 'Olecko';
UPDATE marketing_cities SET population = 9 WHERE name = 'Olsztynek';
UPDATE marketing_cities SET population = 9 WHERE name = 'Koźmin Wielkopolski';
UPDATE marketing_cities SET population = 9 WHERE name = 'Zbąszyń';
UPDATE marketing_cities SET population = 9 WHERE name = 'Kórnik';
UPDATE marketing_cities SET population = 9 WHERE name = 'Barlinek';
UPDATE marketing_cities SET population = 8 WHERE name = 'Kowary';
UPDATE marketing_cities SET population = 8 WHERE name = 'Piechowice';
UPDATE marketing_cities SET population = 8 WHERE name = 'Ząbkowice Śląskie';
UPDATE marketing_cities SET population = 8 WHERE name = 'Kruszwica';
UPDATE marketing_cities SET population = 8 WHERE name = 'Chełmża';
UPDATE marketing_cities SET population = 8 WHERE name = 'Rzepin';
UPDATE marketing_cities SET population = 8 WHERE name = 'Szprotawa';
UPDATE marketing_cities SET population = 8 WHERE name = 'Koluszki';
UPDATE marketing_cities SET population = 8 WHERE name = 'Sułkowice';
UPDATE marketing_cities SET population = 8 WHERE name = 'Tuchów';
UPDATE marketing_cities SET population = 8 WHERE name = 'Łosice';
UPDATE marketing_cities SET population = 8 WHERE name = 'Mrozy';
UPDATE marketing_cities SET population = 8 WHERE name = 'Grodków';
UPDATE marketing_cities SET population = 8 WHERE name = 'Paczków';
UPDATE marketing_cities SET population = 8 WHERE name = 'Niemodlin';
UPDATE marketing_cities SET population = 8 WHERE name = 'Głogówek';
UPDATE marketing_cities SET population = 8 WHERE name = 'Ustrzyki Dolne';
UPDATE marketing_cities SET population = 8 WHERE name = 'Dynów';
UPDATE marketing_cities SET population = 8 WHERE name = 'Choroszcz';
UPDATE marketing_cities SET population = 8 WHERE name = 'Czarna Białostocka';
UPDATE marketing_cities SET population = 8 WHERE name = 'Michałowo';
UPDATE marketing_cities SET population = 8 WHERE name = 'Czarne';
UPDATE marketing_cities SET population = 8 WHERE name = 'Gniew';
UPDATE marketing_cities SET population = 8 WHERE name = 'Sławków';
UPDATE marketing_cities SET population = 8 WHERE name = 'Woźniki';
UPDATE marketing_cities SET population = 8 WHERE name = 'Poręba';
UPDATE marketing_cities SET population = 8 WHERE name = 'Staszów';
UPDATE marketing_cities SET population = 8 WHERE name = 'Biskupiec';
UPDATE marketing_cities SET population = 8 WHERE name = 'Wyrzysk';
UPDATE marketing_cities SET population = 8 WHERE name = 'Miłosław';
UPDATE marketing_cities SET population = 8 WHERE name = 'Jastrowie';
UPDATE marketing_cities SET population = 8 WHERE name = 'Złocieniec';
UPDATE marketing_cities SET population = 8 WHERE name = 'Chojna';
UPDATE marketing_cities SET population = 8 WHERE name = 'Barwice';
UPDATE marketing_cities SET population = 8 WHERE name = 'Borne Sulinowo';
UPDATE marketing_cities SET population = 8 WHERE name = 'Łobez';
UPDATE marketing_cities SET population = 7 WHERE name = 'Góra';
UPDATE marketing_cities SET population = 7 WHERE name = 'Polanica-Zdrój';
UPDATE marketing_cities SET population = 7 WHERE name = 'Olszyna';
UPDATE marketing_cities SET population = 7 WHERE name = 'Ścinawa';
UPDATE marketing_cities SET population = 7 WHERE name = 'Ziębice';
UPDATE marketing_cities SET population = 7 WHERE name = 'Kamień Krajeński';
UPDATE marketing_cities SET population = 7 WHERE name = 'Łabiszyn';
UPDATE marketing_cities SET population = 7 WHERE name = 'Parczew';
UPDATE marketing_cities SET population = 7 WHERE name = 'Ryki';
UPDATE marketing_cities SET population = 7 WHERE name = 'Drezdenko';
UPDATE marketing_cities SET population = 7 WHERE name = 'Rzgów';
UPDATE marketing_cities SET population = 7 WHERE name = 'Pajęczno';
UPDATE marketing_cities SET population = 7 WHERE name = 'Stryków';
UPDATE marketing_cities SET population = 7 WHERE name = 'Alwernia';
UPDATE marketing_cities SET population = 7 WHERE name = 'Biecz';
UPDATE marketing_cities SET population = 7 WHERE name = 'Szczawnica';
UPDATE marketing_cities SET population = 7 WHERE name = 'Wolbrom';
UPDATE marketing_cities SET population = 7 WHERE name = 'Kalwaria Zebrzydowska';
UPDATE marketing_cities SET population = 7 WHERE name = 'Maków Mazowiecki';
UPDATE marketing_cities SET population = 7 WHERE name = 'Halinów';
UPDATE marketing_cities SET population = 7 WHERE name = 'Tłuszcz';
UPDATE marketing_cities SET population = 7 WHERE name = 'Leżajsk';
UPDATE marketing_cities SET population = 7 WHERE name = 'Lubaczów';
UPDATE marketing_cities SET population = 7 WHERE name = 'Rudnik nad Sanem';
UPDATE marketing_cities SET population = 7 WHERE name = 'Boguchwała';
UPDATE marketing_cities SET population = 7 WHERE name = 'Lesko';
UPDATE marketing_cities SET population = 7 WHERE name = 'Kolno';
UPDATE marketing_cities SET population = 7 WHERE name = 'Szczyrk';
UPDATE marketing_cities SET population = 7 WHERE name = 'Łazy';
UPDATE marketing_cities SET population = 7 WHERE name = 'Połaniec';
UPDATE marketing_cities SET population = 7 WHERE name = 'Trzemeszno';
UPDATE marketing_cities SET population = 7 WHERE name = 'Witkowo';
UPDATE marketing_cities SET population = 7 WHERE name = 'Pogorzela';
UPDATE marketing_cities SET population = 7 WHERE name = 'Rakoniewice';
UPDATE marketing_cities SET population = 7 WHERE name = 'Pniewy';
UPDATE marketing_cities SET population = 7 WHERE name = 'Stepnica';
UPDATE marketing_cities SET population = 6 WHERE name = 'Duszniki-Zdrój';
UPDATE marketing_cities SET population = 6 WHERE name = 'Radków';
UPDATE marketing_cities SET population = 6 WHERE name = 'Lwówek Śląski';
UPDATE marketing_cities SET population = 6 WHERE name = 'Chocianów';
UPDATE marketing_cities SET population = 6 WHERE name = 'Przemków';
UPDATE marketing_cities SET population = 6 WHERE name = 'Janikowo';
UPDATE marketing_cities SET population = 6 WHERE name = 'Poniatowa';
UPDATE marketing_cities SET population = 6 WHERE name = 'Witnica';
UPDATE marketing_cities SET population = 6 WHERE name = 'Cybinka';
UPDATE marketing_cities SET population = 6 WHERE name = 'Nowogród Bobrzański';
UPDATE marketing_cities SET population = 6 WHERE name = 'Zelów';
UPDATE marketing_cities SET population = 6 WHERE name = 'Łęczyca';
UPDATE marketing_cities SET population = 6 WHERE name = 'Uniejów';
UPDATE marketing_cities SET population = 6 WHERE name = 'Krzeszowice';
UPDATE marketing_cities SET population = 6 WHERE name = 'Słomniki';
UPDATE marketing_cities SET population = 6 WHERE name = 'Grybów';
UPDATE marketing_cities SET population = 6 WHERE name = 'Czarny Dunajec';
UPDATE marketing_cities SET population = 6 WHERE name = 'Maków Podhalański';
UPDATE marketing_cities SET population = 6 WHERE name = 'Żabno';
UPDATE marketing_cities SET population = 6 WHERE name = 'Kietrz';
UPDATE marketing_cities SET population = 6 WHERE name = 'Zdzieszowice';
UPDATE marketing_cities SET population = 6 WHERE name = 'Gorzów Śląski';
UPDATE marketing_cities SET population = 6 WHERE name = 'Nowa Sarzyna';
UPDATE marketing_cities SET population = 6 WHERE name = 'Miastko';
UPDATE marketing_cities SET population = 6 WHERE name = 'Nowy Staw';
UPDATE marketing_cities SET population = 6 WHERE name = 'Ogrodzieniec';
UPDATE marketing_cities SET population = 6 WHERE name = 'Kazimierza Wielka';
UPDATE marketing_cities SET population = 6 WHERE name = 'Opatów';
UPDATE marketing_cities SET population = 6 WHERE name = 'Ryn';
UPDATE marketing_cities SET population = 6 WHERE name = 'Reszel';
UPDATE marketing_cities SET population = 6 WHERE name = 'Orzysz';
UPDATE marketing_cities SET population = 6 WHERE name = 'Krzyż Wielkopolski';
UPDATE marketing_cities SET population = 6 WHERE name = 'Poniec';
UPDATE marketing_cities SET population = 6 WHERE name = 'Kobylin';
UPDATE marketing_cities SET population = 6 WHERE name = 'Ujście';
UPDATE marketing_cities SET population = 6 WHERE name = 'Stęszew';
UPDATE marketing_cities SET population = 6 WHERE name = 'Książ Wielkopolski';
UPDATE marketing_cities SET population = 6 WHERE name = 'Pyzdry';
UPDATE marketing_cities SET population = 6 WHERE name = 'Pełczyce';
UPDATE marketing_cities SET population = 6 WHERE name = 'Mirosławiec';
UPDATE marketing_cities SET population = 5 WHERE name = 'Karpacz';
UPDATE marketing_cities SET population = 5 WHERE name = 'Szczawnica';
UPDATE marketing_cities SET population = 5 WHERE name = 'Prochowice';
UPDATE marketing_cities SET population = 5 WHERE name = 'Leśna';
UPDATE marketing_cities SET population = 5 WHERE name = 'Głuszyca';
UPDATE marketing_cities SET population = 5 WHERE name = 'Jabłonowo Pomorskie';
UPDATE marketing_cities SET population = 5 WHERE name = 'Strzelno';
UPDATE marketing_cities SET population = 5 WHERE name = 'Mrocza';
UPDATE marketing_cities SET population = 5 WHERE name = 'Piotrków Kujawski';
UPDATE marketing_cities SET population = 5 WHERE name = 'Więcbork';
UPDATE marketing_cities SET population = 5 WHERE name = 'Nowe';
UPDATE marketing_cities SET population = 5 WHERE name = 'Brześć Kujawski';
UPDATE marketing_cities SET population = 5 WHERE name = 'Bełżyce';
UPDATE marketing_cities SET population = 5 WHERE name = 'Trzciel';
UPDATE marketing_cities SET population = 5 WHERE name = 'Bytom Odrzański';
UPDATE marketing_cities SET population = 5 WHERE name = 'Ośno Lubuskie';
UPDATE marketing_cities SET population = 5 WHERE name = 'Torzym';
UPDATE marketing_cities SET population = 5 WHERE name = 'Czerwieńsk';
UPDATE marketing_cities SET population = 5 WHERE name = 'Jasień';
UPDATE marketing_cities SET population = 5 WHERE name = 'Dobczyce';
UPDATE marketing_cities SET population = 5 WHERE name = 'Chełmek';
UPDATE marketing_cities SET population = 5 WHERE name = 'Zator';
UPDATE marketing_cities SET population = 5 WHERE name = 'Dobre';
UPDATE marketing_cities SET population = 5 WHERE name = 'Tarczyn';
UPDATE marketing_cities SET population = 5 WHERE name = 'Gąbin';
UPDATE marketing_cities SET population = 5 WHERE name = 'Jedlnia-Letnisko';
UPDATE marketing_cities SET population = 5 WHERE name = 'Skaryszew';
UPDATE marketing_cities SET population = 5 WHERE name = 'Byczyna';
UPDATE marketing_cities SET population = 5 WHERE name = 'Gogolin';
UPDATE marketing_cities SET population = 5 WHERE name = 'Korfantów';
UPDATE marketing_cities SET population = 5 WHERE name = 'Otmuchów';
UPDATE marketing_cities SET population = 5 WHERE name = 'Praszka';
UPDATE marketing_cities SET population = 5 WHERE name = 'Zawadzkie';
UPDATE marketing_cities SET population = 5 WHERE name = 'Radymno';
UPDATE marketing_cities SET population = 5 WHERE name = 'Tyczyn';
UPDATE marketing_cities SET population = 5 WHERE name = 'Supraśl';
UPDATE marketing_cities SET population = 5 WHERE name = 'Szczuczyn';
UPDATE marketing_cities SET population = 5 WHERE name = 'Krynki';
UPDATE marketing_cities SET population = 5 WHERE name = 'Czyżew';
UPDATE marketing_cities SET population = 5 WHERE name = 'Hel';
UPDATE marketing_cities SET population = 5 WHERE name = 'Czarna Woda';
UPDATE marketing_cities SET population = 5 WHERE name = 'Wilamowice';
UPDATE marketing_cities SET population = 5 WHERE name = 'Kalety';
UPDATE marketing_cities SET population = 5 WHERE name = 'Sędziszów';
UPDATE marketing_cities SET population = 5 WHERE name = 'Radoszyce';
UPDATE marketing_cities SET population = 5 WHERE name = 'Osiek';
UPDATE marketing_cities SET population = 5 WHERE name = 'Lidzbark';
UPDATE marketing_cities SET population = 5 WHERE name = 'Susz';
UPDATE marketing_cities SET population = 5 WHERE name = 'Mikołajki';
UPDATE marketing_cities SET population = 5 WHERE name = 'Budzyń';
UPDATE marketing_cities SET population = 5 WHERE name = 'Żerków';
UPDATE marketing_cities SET population = 5 WHERE name = 'Rychwał';
UPDATE marketing_cities SET population = 5 WHERE name = 'Nowe Skalmierzyce';
UPDATE marketing_cities SET population = 5 WHERE name = 'Kaczory';
UPDATE marketing_cities SET population = 5 WHERE name = 'Łobżenica';
UPDATE marketing_cities SET population = 5 WHERE name = 'Miejska Górka';
UPDATE marketing_cities SET population = 5 WHERE name = 'Gołańcz';
UPDATE marketing_cities SET population = 5 WHERE name = 'Tychowo';
UPDATE marketing_cities SET population = 5 WHERE name = 'Czaplinek';
UPDATE marketing_cities SET population = 5 WHERE name = 'Gościno';
UPDATE marketing_cities SET population = 5 WHERE name = 'Połczyn-Zdrój';
UPDATE marketing_cities SET population = 4 WHERE name = 'Wąsosz';
UPDATE marketing_cities SET population = 4 WHERE name = 'Lubawka';
UPDATE marketing_cities SET population = 4 WHERE name = 'Lądek-Zdrój';
UPDATE marketing_cities SET population = 4 WHERE name = 'Świeradów-Zdrój';
UPDATE marketing_cities SET population = 4 WHERE name = 'Wleń';
UPDATE marketing_cities SET population = 4 WHERE name = 'Twardogóra';
UPDATE marketing_cities SET population = 4 WHERE name = 'Żarów';
UPDATE marketing_cities SET population = 4 WHERE name = 'Kamieniec Ząbkowicki';
UPDATE marketing_cities SET population = 4 WHERE name = 'Zawidów';
UPDATE marketing_cities SET population = 4 WHERE name = 'Wojcieszów';
UPDATE marketing_cities SET population = 4 WHERE name = 'Gniewkowo';
UPDATE marketing_cities SET population = 4 WHERE name = 'Kcynia';
UPDATE marketing_cities SET population = 4 WHERE name = 'Radziejów';
UPDATE marketing_cities SET population = 4 WHERE name = 'Pruszcz';
UPDATE marketing_cities SET population = 4 WHERE name = 'Kowal';
UPDATE marketing_cities SET population = 4 WHERE name = 'Janowiec Wielkopolski';
UPDATE marketing_cities SET population = 4 WHERE name = 'Kazimierz Dolny';
UPDATE marketing_cities SET population = 4 WHERE name = 'Końskowola';
UPDATE marketing_cities SET population = 4 WHERE name = 'Szczebrzeszyn';
UPDATE marketing_cities SET population = 4 WHERE name = 'Zbąszynek';
UPDATE marketing_cities SET population = 4 WHERE name = 'Kargowa';
UPDATE marketing_cities SET population = 4 WHERE name = 'Iłowa';
UPDATE marketing_cities SET population = 4 WHERE name = 'Żychlin';
UPDATE marketing_cities SET population = 4 WHERE name = 'Rozprza';
UPDATE marketing_cities SET population = 4 WHERE name = 'Szczucin';
UPDATE marketing_cities SET population = 4 WHERE name = 'Proszowice';
UPDATE marketing_cities SET population = 4 WHERE name = 'Ciężkowice';
UPDATE marketing_cities SET population = 4 WHERE name = 'Pilawa';
UPDATE marketing_cities SET population = 4 WHERE name = 'Żelechów';
UPDATE marketing_cities SET population = 4 WHERE name = 'Sanniki';
UPDATE marketing_cities SET population = 4 WHERE name = 'Podkowa Leśna';
UPDATE marketing_cities SET population = 4 WHERE name = 'Różan';
UPDATE marketing_cities SET population = 4 WHERE name = 'Kałuszyn';
UPDATE marketing_cities SET population = 4 WHERE name = 'Zakroczym';
UPDATE marketing_cities SET population = 4 WHERE name = 'Brok';
UPDATE marketing_cities SET population = 4 WHERE name = 'Drobin';
UPDATE marketing_cities SET population = 4 WHERE name = 'Iłża';
UPDATE marketing_cities SET population = 4 WHERE name = 'Wołczyn';
UPDATE marketing_cities SET population = 4 WHERE name = 'Tułowice';
UPDATE marketing_cities SET population = 4 WHERE name = 'Brzostek';
UPDATE marketing_cities SET population = 4 WHERE name = 'Błażowa';
UPDATE marketing_cities SET population = 4 WHERE name = 'Sokołów Małopolski';
UPDATE marketing_cities SET population = 4 WHERE name = 'Stawiski';
UPDATE marketing_cities SET population = 4 WHERE name = 'Drohiczyn';
UPDATE marketing_cities SET population = 4 WHERE name = 'Dąbrowa Białostocka';
UPDATE marketing_cities SET population = 4 WHERE name = 'Brusy';
UPDATE marketing_cities SET population = 4 WHERE name = 'Kępice';
UPDATE marketing_cities SET population = 4 WHERE name = 'Koniecpol';
UPDATE marketing_cities SET population = 4 WHERE name = 'Przyrów';
UPDATE marketing_cities SET population = 4 WHERE name = 'Ćmielów';
UPDATE marketing_cities SET population = 4 WHERE name = 'Włoszczowa';
UPDATE marketing_cities SET population = 4 WHERE name = 'Jeziorany';
UPDATE marketing_cities SET population = 4 WHERE name = 'Miłomłyn';
UPDATE marketing_cities SET population = 4 WHERE name = 'Ruciane-Nida';
UPDATE marketing_cities SET population = 4 WHERE name = 'Szamocin';
UPDATE marketing_cities SET population = 4 WHERE name = 'Kłecko';
UPDATE marketing_cities SET population = 4 WHERE name = 'Opatówek';
UPDATE marketing_cities SET population = 4 WHERE name = 'Kłodawa';
UPDATE marketing_cities SET population = 4 WHERE name = 'Zduny';
UPDATE marketing_cities SET population = 4 WHERE name = 'Osieczna';
UPDATE marketing_cities SET population = 4 WHERE name = 'Rydzyna';
UPDATE marketing_cities SET population = 4 WHERE name = 'Wysoka';
UPDATE marketing_cities SET population = 4 WHERE name = 'Bojanowo';
UPDATE marketing_cities SET population = 4 WHERE name = 'Krajenka';
UPDATE marketing_cities SET population = 4 WHERE name = 'Recz';
UPDATE marketing_cities SET population = 4 WHERE name = 'Mieszkowice';
UPDATE marketing_cities SET population = 4 WHERE name = 'Międzyzdroje';
UPDATE marketing_cities SET population = 4 WHERE name = 'Wolin';
UPDATE marketing_cities SET population = 4 WHERE name = 'Mielno';
UPDATE marketing_cities SET population = 3 WHERE name = 'Nowogrodziec';
UPDATE marketing_cities SET population = 3 WHERE name = 'Piława Górna';
UPDATE marketing_cities SET population = 3 WHERE name = 'Szklarska Poręba';
UPDATE marketing_cities SET population = 3 WHERE name = 'Stronie Śląskie';
UPDATE marketing_cities SET population = 3 WHERE name = 'Gryfów Śląski';
UPDATE marketing_cities SET population = 3 WHERE name = 'Bierutów';
UPDATE marketing_cities SET population = 3 WHERE name = 'Pakość';
UPDATE marketing_cities SET population = 3 WHERE name = 'Skępe';
UPDATE marketing_cities SET population = 3 WHERE name = 'Piszczac';
UPDATE marketing_cities SET population = 3 WHERE name = 'Rejowiec Fabryczny';
UPDATE marketing_cities SET population = 3 WHERE name = 'Izbica';
UPDATE marketing_cities SET population = 3 WHERE name = 'Annopol';
UPDATE marketing_cities SET population = 3 WHERE name = 'Kock';
UPDATE marketing_cities SET population = 3 WHERE name = 'Stoczek Łukowski';
UPDATE marketing_cities SET population = 3 WHERE name = 'Nałęczów';
UPDATE marketing_cities SET population = 3 WHERE name = 'Otyń';
UPDATE marketing_cities SET population = 3 WHERE name = 'Dobiegniew';
UPDATE marketing_cities SET population = 3 WHERE name = 'Małomice';
UPDATE marketing_cities SET population = 3 WHERE name = 'Krośniewice';
UPDATE marketing_cities SET population = 3 WHERE name = 'Kiernozia';
UPDATE marketing_cities SET population = 3 WHERE name = 'Drzewica';
UPDATE marketing_cities SET population = 3 WHERE name = 'Poddębice';
UPDATE marketing_cities SET population = 3 WHERE name = 'Kamieńsk';
UPDATE marketing_cities SET population = 3 WHERE name = 'Błaszki';
UPDATE marketing_cities SET population = 3 WHERE name = 'Warta';
UPDATE marketing_cities SET population = 3 WHERE name = 'Złoczew';
UPDATE marketing_cities SET population = 3 WHERE name = 'Skała';
UPDATE marketing_cities SET population = 3 WHERE name = 'Świątniki Górne';
UPDATE marketing_cities SET population = 3 WHERE name = 'Piwniczna-Zdrój';
UPDATE marketing_cities SET population = 3 WHERE name = 'Glinojeck';
UPDATE marketing_cities SET population = 3 WHERE name = 'Mogielnica';
UPDATE marketing_cities SET population = 3 WHERE name = 'Nowe Miasto nad Pilicą';
UPDATE marketing_cities SET population = 3 WHERE name = 'Głowaczów';
UPDATE marketing_cities SET population = 3 WHERE name = 'Lipsko';
UPDATE marketing_cities SET population = 3 WHERE name = 'Myszyniec';
UPDATE marketing_cities SET population = 3 WHERE name = 'Sochocin';
UPDATE marketing_cities SET population = 3 WHERE name = 'Mordy';
UPDATE marketing_cities SET population = 3 WHERE name = 'Zwoleń';
UPDATE marketing_cities SET population = 3 WHERE name = 'Baborów';
UPDATE marketing_cities SET population = 3 WHERE name = 'Pilzno';
UPDATE marketing_cities SET population = 3 WHERE name = 'Radomyśl Wielki';
UPDATE marketing_cities SET population = 3 WHERE name = 'Zagórz';
UPDATE marketing_cities SET population = 3 WHERE name = 'Zaklików';
UPDATE marketing_cities SET population = 3 WHERE name = 'Baranów Sandomierski';
UPDATE marketing_cities SET population = 3 WHERE name = 'Sejny';
UPDATE marketing_cities SET population = 3 WHERE name = 'Ciechanowiec';
UPDATE marketing_cities SET population = 3 WHERE name = 'Łeba';
UPDATE marketing_cities SET population = 3 WHERE name = 'Jastarnia';
UPDATE marketing_cities SET population = 3 WHERE name = 'Kobylnica';
UPDATE marketing_cities SET population = 3 WHERE name = 'Dzierzgoń';
UPDATE marketing_cities SET population = 3 WHERE name = 'Strumień';
UPDATE marketing_cities SET population = 3 WHERE name = 'Szczekociny';
UPDATE marketing_cities SET population = 3 WHERE name = 'Małogoszcz';
UPDATE marketing_cities SET population = 3 WHERE name = 'Chęciny';
UPDATE marketing_cities SET population = 3 WHERE name = 'Morawica';
UPDATE marketing_cities SET population = 3 WHERE name = 'Piekoszów';
UPDATE marketing_cities SET population = 3 WHERE name = 'Gowarczów';
UPDATE marketing_cities SET population = 3 WHERE name = 'Ożarów';
UPDATE marketing_cities SET population = 3 WHERE name = 'Bisztynek';
UPDATE marketing_cities SET population = 3 WHERE name = 'Sępopol';
UPDATE marketing_cities SET population = 3 WHERE name = 'Tolkmicko';
UPDATE marketing_cities SET population = 3 WHERE name = 'Zalewo';
UPDATE marketing_cities SET population = 3 WHERE name = 'Korsze';
UPDATE marketing_cities SET population = 3 WHERE name = 'Pasym';
UPDATE marketing_cities SET population = 3 WHERE name = 'Wielbark';
UPDATE marketing_cities SET population = 3 WHERE name = 'Margonin';
UPDATE marketing_cities SET population = 3 WHERE name = 'Wieleń';
UPDATE marketing_cities SET population = 3 WHERE name = 'Czerniejewo';
UPDATE marketing_cities SET population = 3 WHERE name = 'Krobia';
UPDATE marketing_cities SET population = 3 WHERE name = 'Kleczew';
UPDATE marketing_cities SET population = 3 WHERE name = 'Czempiń';
UPDATE marketing_cities SET population = 3 WHERE name = 'Sieraków';
UPDATE marketing_cities SET population = 3 WHERE name = 'Raszków';
UPDATE marketing_cities SET population = 3 WHERE name = 'Grabów nad Prosną';
UPDATE marketing_cities SET population = 3 WHERE name = 'Buk';
UPDATE marketing_cities SET population = 3 WHERE name = 'Jutrosin';
UPDATE marketing_cities SET population = 3 WHERE name = 'Zagórów';
UPDATE marketing_cities SET population = 3 WHERE name = 'Mieścisko';
UPDATE marketing_cities SET population = 3 WHERE name = 'Skoki';
UPDATE marketing_cities SET population = 3 WHERE name = 'Karlino';
UPDATE marketing_cities SET population = 3 WHERE name = 'Maszewo';
UPDATE marketing_cities SET population = 3 WHERE name = 'Płoty';
UPDATE marketing_cities SET population = 3 WHERE name = 'Moryń';
UPDATE marketing_cities SET population = 3 WHERE name = 'Lipiany';
UPDATE marketing_cities SET population = 3 WHERE name = 'Chociwel';
UPDATE marketing_cities SET population = 3 WHERE name = 'Człopa';
UPDATE marketing_cities SET population = 2 WHERE name = 'Międzylesie';
UPDATE marketing_cities SET population = 2 WHERE name = 'Mirsk';
UPDATE marketing_cities SET population = 2 WHERE name = 'Miękinia';
UPDATE marketing_cities SET population = 2 WHERE name = 'Prusice';
UPDATE marketing_cities SET population = 2 WHERE name = 'Jedlina-Zdrój';
UPDATE marketing_cities SET population = 2 WHERE name = 'Węgliniec';
UPDATE marketing_cities SET population = 2 WHERE name = 'Świerzawa';
UPDATE marketing_cities SET population = 2 WHERE name = 'Nieszawa';
UPDATE marketing_cities SET population = 2 WHERE name = 'Kowalewo Pomorskie';
UPDATE marketing_cities SET population = 2 WHERE name = 'Kikół';
UPDATE marketing_cities SET population = 2 WHERE name = 'Izbica Kujawska';
UPDATE marketing_cities SET population = 2 WHERE name = 'Goraj';
UPDATE marketing_cities SET population = 2 WHERE name = 'Siedliszcze';
UPDATE marketing_cities SET population = 2 WHERE name = 'Rejowiec';
UPDATE marketing_cities SET population = 2 WHERE name = 'Wąwolnica';
UPDATE marketing_cities SET population = 2 WHERE name = 'Czemierniki';
UPDATE marketing_cities SET population = 2 WHERE name = 'Łaszczów';
UPDATE marketing_cities SET population = 2 WHERE name = 'Tyszowce';
UPDATE marketing_cities SET population = 2 WHERE name = 'Zwierzyniec';
UPDATE marketing_cities SET population = 2 WHERE name = 'Nowe Miasteczko';
UPDATE marketing_cities SET population = 2 WHERE name = 'Babimost';
UPDATE marketing_cities SET population = 2 WHERE name = 'Łęknica';
UPDATE marketing_cities SET population = 2 WHERE name = 'Sława';
UPDATE marketing_cities SET population = 2 WHERE name = 'Lutomiersz';
UPDATE marketing_cities SET population = 2 WHERE name = 'Wolbórz';
UPDATE marketing_cities SET population = 2 WHERE name = 'Bolimów';
UPDATE marketing_cities SET population = 2 WHERE name = 'Ujazd';
UPDATE marketing_cities SET population = 2 WHERE name = 'Lututów';
UPDATE marketing_cities SET population = 2 WHERE name = 'Jeżów';
UPDATE marketing_cities SET population = 2 WHERE name = 'Nowy Wiśnicz';
UPDATE marketing_cities SET population = 2 WHERE name = 'Muszyna';
UPDATE marketing_cities SET population = 2 WHERE name = 'Maciejowice';
UPDATE marketing_cities SET population = 2 WHERE name = 'Magnuszew';
UPDATE marketing_cities SET population = 2 WHERE name = 'Sienno';
UPDATE marketing_cities SET population = 2 WHERE name = 'Siennica';
UPDATE marketing_cities SET population = 2 WHERE name = 'Wyszogród';
UPDATE marketing_cities SET population = 2 WHERE name = 'Nowe Miasto';
UPDATE marketing_cities SET population = 2 WHERE name = 'Lubowidz';
UPDATE marketing_cities SET population = 2 WHERE name = 'Prószków';
UPDATE marketing_cities SET population = 2 WHERE name = 'Biała';
UPDATE marketing_cities SET population = 2 WHERE name = 'Dukla';
UPDATE marketing_cities SET population = 2 WHERE name = 'Rymanów';
UPDATE marketing_cities SET population = 2 WHERE name = 'Narol';
UPDATE marketing_cities SET population = 2 WHERE name = 'Przecław';
UPDATE marketing_cities SET population = 2 WHERE name = 'Ulanów';
UPDATE marketing_cities SET population = 2 WHERE name = 'Jawornik Polski';
UPDATE marketing_cities SET population = 2 WHERE name = 'Zabłudów';
UPDATE marketing_cities SET population = 2 WHERE name = 'Brańsk';
UPDATE marketing_cities SET population = 2 WHERE name = 'Kleszczele';
UPDATE marketing_cities SET population = 2 WHERE name = 'Nowogród';
UPDATE marketing_cities SET population = 2 WHERE name = 'Szepietowo';
UPDATE marketing_cities SET population = 2 WHERE name = 'Skórcz';
UPDATE marketing_cities SET population = 2 WHERE name = 'Sośnicowice';
UPDATE marketing_cities SET population = 2 WHERE name = 'Toszek';
UPDATE marketing_cities SET population = 2 WHERE name = 'Krzanowice';
UPDATE marketing_cities SET population = 2 WHERE name = 'Włodowice';
UPDATE marketing_cities SET population = 2 WHERE name = 'Wodzisław';
UPDATE marketing_cities SET population = 2 WHERE name = 'Bodzentyn';
UPDATE marketing_cities SET population = 2 WHERE name = 'Daleszyce';
UPDATE marketing_cities SET population = 2 WHERE name = 'Łagów';
UPDATE marketing_cities SET population = 2 WHERE name = 'Łopuszno';
UPDATE marketing_cities SET population = 2 WHERE name = 'Stąporków';
UPDATE marketing_cities SET population = 2 WHERE name = 'Kunów';
UPDATE marketing_cities SET population = 2 WHERE name = 'Suchedniów';
UPDATE marketing_cities SET population = 2 WHERE name = 'Wąchock';
UPDATE marketing_cities SET population = 2 WHERE name = 'Szydłów';
UPDATE marketing_cities SET population = 2 WHERE name = 'Frombork';
UPDATE marketing_cities SET population = 2 WHERE name = 'Pieniężno';
UPDATE marketing_cities SET population = 2 WHERE name = 'Miłakowo';
UPDATE marketing_cities SET population = 2 WHERE name = 'Biała Piska';
UPDATE marketing_cities SET population = 2 WHERE name = 'Jaraczewo';
UPDATE marketing_cities SET population = 2 WHERE name = 'Koźminek';
UPDATE marketing_cities SET population = 2 WHERE name = 'Stawiszyn';
UPDATE marketing_cities SET population = 2 WHERE name = 'Przedecz';
UPDATE marketing_cities SET population = 2 WHERE name = 'Golina';
UPDATE marketing_cities SET population = 2 WHERE name = 'Ślesin';
UPDATE marketing_cities SET population = 2 WHERE name = 'Krzywiń';
UPDATE marketing_cities SET population = 2 WHERE name = 'Lwówek';
UPDATE marketing_cities SET population = 2 WHERE name = 'Odolanów';
UPDATE marketing_cities SET population = 2 WHERE name = 'Dobrzyca';
UPDATE marketing_cities SET population = 2 WHERE name = 'Obrzycko';
UPDATE marketing_cities SET population = 2 WHERE name = 'Tuliszków';
UPDATE marketing_cities SET population = 2 WHERE name = 'Kalisz Pomorski';
UPDATE marketing_cities SET population = 2 WHERE name = 'Bobolice';
UPDATE marketing_cities SET population = 2 WHERE name = 'Nowe Warpno';
UPDATE marketing_cities SET population = 2 WHERE name = 'Tuczno';
UPDATE marketing_cities SET population = 1 WHERE name = 'Niemcza';
UPDATE marketing_cities SET population = 1 WHERE name = 'Lubomierz';
UPDATE marketing_cities SET population = 1 WHERE name = 'Międzybórz';
UPDATE marketing_cities SET population = 1 WHERE name = 'Mieroszów';
UPDATE marketing_cities SET population = 1 WHERE name = 'Bardo';
UPDATE marketing_cities SET population = 1 WHERE name = 'Złoty Stok';
UPDATE marketing_cities SET population = 1 WHERE name = 'Łasin';
UPDATE marketing_cities SET population = 1 WHERE name = 'Dobrzyń nad Wisłą';
UPDATE marketing_cities SET population = 1 WHERE name = 'Chodecz';
UPDATE marketing_cities SET population = 1 WHERE name = 'Lubraniec';
UPDATE marketing_cities SET population = 1 WHERE name = 'Gąsawa';
UPDATE marketing_cities SET population = 1 WHERE name = 'Frampol';
UPDATE marketing_cities SET population = 1 WHERE name = 'Tarnogród';
UPDATE marketing_cities SET population = 1 WHERE name = 'Kamionka';
UPDATE marketing_cities SET population = 1 WHERE name = 'Ostrów Lubelski';
UPDATE marketing_cities SET population = 1 WHERE name = 'Józefów nad Wisłą';
UPDATE marketing_cities SET population = 1 WHERE name = 'Kurów';
UPDATE marketing_cities SET population = 1 WHERE name = 'Lubycza Królewska';
UPDATE marketing_cities SET population = 1 WHERE name = 'Lubniewice';
UPDATE marketing_cities SET population = 1 WHERE name = 'Gozdnica';
UPDATE marketing_cities SET population = 1 WHERE name = 'Szlichtyngowa';
UPDATE marketing_cities SET population = 1 WHERE name = 'Grabów';
UPDATE marketing_cities SET population = 1 WHERE name = 'Białaczów';
UPDATE marketing_cities SET population = 1 WHERE name = 'Przedbórz';
UPDATE marketing_cities SET population = 1 WHERE name = 'Szadek';
UPDATE marketing_cities SET population = 1 WHERE name = 'Parzęczew';
UPDATE marketing_cities SET population = 1 WHERE name = 'Czchów';
UPDATE marketing_cities SET population = 1 WHERE name = 'Bobowa';
UPDATE marketing_cities SET population = 1 WHERE name = 'Koszyce';
UPDATE marketing_cities SET population = 1 WHERE name = 'Nowe Brzesko';
UPDATE marketing_cities SET population = 1 WHERE name = 'Radłów';
UPDATE marketing_cities SET population = 1 WHERE name = 'Rytle';
UPDATE marketing_cities SET population = 1 WHERE name = 'Zakliczyn';
UPDATE marketing_cities SET population = 1 WHERE name = 'Ciepielów';
UPDATE marketing_cities SET population = 1 WHERE name = 'Solec nad Wisłą';
UPDATE marketing_cities SET population = 1 WHERE name = 'Latowicz';
UPDATE marketing_cities SET population = 1 WHERE name = 'Osieck';
UPDATE marketing_cities SET population = 1 WHERE name = 'Bodzanów';
UPDATE marketing_cities SET population = 1 WHERE name = 'Chorzele';
UPDATE marketing_cities SET population = 1 WHERE name = 'Gielniów';
UPDATE marketing_cities SET population = 1 WHERE name = 'Jastrząb';
UPDATE marketing_cities SET population = 1 WHERE name = 'Jadów';
UPDATE marketing_cities SET population = 1 WHERE name = 'Kazanów';
UPDATE marketing_cities SET population = 1 WHERE name = 'Wiskitki';
UPDATE marketing_cities SET population = 1 WHERE name = 'Strzeleczki';
UPDATE marketing_cities SET population = 1 WHERE name = 'Dobrodzień';
UPDATE marketing_cities SET population = 1 WHERE name = 'Leśnica';
UPDATE marketing_cities SET population = 1 WHERE name = 'Pruchnik';
UPDATE marketing_cities SET population = 1 WHERE name = 'Kołaczyce';
UPDATE marketing_cities SET population = 1 WHERE name = 'Iwonicz-Zdrój';
UPDATE marketing_cities SET population = 1 WHERE name = 'Oleszyce';
UPDATE marketing_cities SET population = 1 WHERE name = 'Bircza';
UPDATE marketing_cities SET population = 1 WHERE name = 'Dubiecko';
UPDATE marketing_cities SET population = 1 WHERE name = 'Lipsk';
UPDATE marketing_cities SET population = 1 WHERE name = 'Suraż';
UPDATE marketing_cities SET population = 1 WHERE name = 'Tykocin';
UPDATE marketing_cities SET population = 1 WHERE name = 'Rajgród';
UPDATE marketing_cities SET population = 1 WHERE name = 'Jedwabne';
UPDATE marketing_cities SET population = 1 WHERE name = 'Goniądz';
UPDATE marketing_cities SET population = 1 WHERE name = 'Knyszyn';
UPDATE marketing_cities SET population = 1 WHERE name = 'Koziegłowy';
UPDATE marketing_cities SET population = 1 WHERE name = 'Pilica';
UPDATE marketing_cities SET population = 1 WHERE name = 'Nowy Korczyn';
UPDATE marketing_cities SET population = 1 WHERE name = 'Pacanów';
UPDATE marketing_cities SET population = 1 WHERE name = 'Opatowiec';
UPDATE marketing_cities SET population = 1 WHERE name = 'Skalbmierz';
UPDATE marketing_cities SET population = 1 WHERE name = 'Nowa Słupia';
UPDATE marketing_cities SET population = 1 WHERE name = 'Iwaniska';
UPDATE marketing_cities SET population = 1 WHERE name = 'Działoszyce';
UPDATE marketing_cities SET population = 1 WHERE name = 'Klimontów';
UPDATE marketing_cities SET population = 1 WHERE name = 'Koprzywnica';
UPDATE marketing_cities SET population = 1 WHERE name = 'Zawichost';
UPDATE marketing_cities SET population = 1 WHERE name = 'Bogoria';
UPDATE marketing_cities SET population = 1 WHERE name = 'Młynary';
UPDATE marketing_cities SET population = 1 WHERE name = 'Borek Wielkopolski';
UPDATE marketing_cities SET population = 1 WHERE name = 'Rychtal';
UPDATE marketing_cities SET population = 1 WHERE name = 'Dąbie';
UPDATE marketing_cities SET population = 1 WHERE name = 'Sompolno';
UPDATE marketing_cities SET population = 1 WHERE name = 'Sulmierzyce';
UPDATE marketing_cities SET population = 1 WHERE name = 'Mikstat';
UPDATE marketing_cities SET population = 1 WHERE name = 'Miasteczko Krajeńskie';
UPDATE marketing_cities SET population = 1 WHERE name = 'Chocz';
UPDATE marketing_cities SET population = 1 WHERE name = 'Ostroróg';
UPDATE marketing_cities SET population = 1 WHERE name = 'Zaniemyśl';
UPDATE marketing_cities SET population = 1 WHERE name = 'Dolsk';
UPDATE marketing_cities SET population = 1 WHERE name = 'Dobra';
UPDATE marketing_cities SET population = 1 WHERE name = 'Okonek';
UPDATE marketing_cities SET population = 1 WHERE name = 'Trzcińsko-Zdrój';
UPDATE marketing_cities SET population = 1 WHERE name = 'Golczewo';
UPDATE marketing_cities SET population = 1 WHERE name = 'Polanów';
UPDATE marketing_cities SET population = 1 WHERE name = 'Suchań';
UPDATE marketing_cities SET population = 1 WHERE name = 'Resko';
UPDATE marketing_cities SET population = 1 WHERE name = 'Węgorzyno';
