-- Population from Wikipedia (2021, actual values)

UPDATE marketing_cities SET population = 1794166 WHERE name = 'Warszawa';
UPDATE marketing_cities SET population = 779966 WHERE name = 'Kraków';
UPDATE marketing_cities SET population = 672185 WHERE name = 'Łódź';
UPDATE marketing_cities SET population = 641928 WHERE name = 'Wrocław';
UPDATE marketing_cities SET population = 532048 WHERE name = 'Poznań';
UPDATE marketing_cities SET population = 470805 WHERE name = 'Gdańsk';
UPDATE marketing_cities SET population = 398255 WHERE name = 'Szczecin';
UPDATE marketing_cities SET population = 344091 WHERE name = 'Bydgoszcz';
UPDATE marketing_cities SET population = 338586 WHERE name = 'Lublin';
UPDATE marketing_cities SET population = 296958 WHERE name = 'Białystok';
UPDATE marketing_cities SET population = 290553 WHERE name = 'Katowice';
UPDATE marketing_cities SET population = 244969 WHERE name = 'Gdynia';
UPDATE marketing_cities SET population = 217530 WHERE name = 'Częstochowa';
UPDATE marketing_cities SET population = 209296 WHERE name = 'Radom';
UPDATE marketing_cities SET population = 198613 WHERE name = 'Toruń';
UPDATE marketing_cities SET population = 197863 WHERE name = 'Rzeszów';
UPDATE marketing_cities SET population = 197586 WHERE name = 'Sosnowiec';
UPDATE marketing_cities SET population = 193415 WHERE name = 'Kielce';
UPDATE marketing_cities SET population = 177049 WHERE name = 'Gliwice';
UPDATE marketing_cities SET population = 171249 WHERE name = 'Olsztyn';
UPDATE marketing_cities SET population = 170924 WHERE name = 'Zabrze';
UPDATE marketing_cities SET population = 169756 WHERE name = 'Bielsko-Biała';
UPDATE marketing_cities SET population = 163255 WHERE name = 'Bytom';
UPDATE marketing_cities SET population = 140892 WHERE name = 'Zielona Góra';
UPDATE marketing_cities SET population = 137128 WHERE name = 'Rybnik';
UPDATE marketing_cities SET population = 136423 WHERE name = 'Ruda Śląska';
UPDATE marketing_cities SET population = 127839 WHERE name = 'Opole';
UPDATE marketing_cities SET population = 126871 WHERE name = 'Tychy';
UPDATE marketing_cities SET population = 122589 WHERE name = 'Gorzów Wielkopolski';
UPDATE marketing_cities SET population = 118582 WHERE name = 'Elbląg';
UPDATE marketing_cities SET population = 118285 WHERE name = 'Dąbrowa Górnicza';
UPDATE marketing_cities SET population = 118268 WHERE name = 'Płock';
UPDATE marketing_cities SET population = 109971 WHERE name = 'Wałbrzych';
UPDATE marketing_cities SET population = 108561 WHERE name = 'Włocławek';
UPDATE marketing_cities SET population = 107498 WHERE name = 'Tarnów';
UPDATE marketing_cities SET population = 106846 WHERE name = 'Chorzów';
UPDATE marketing_cities SET population = 106235 WHERE name = 'Koszalin';
UPDATE marketing_cities SET population = 99106 WHERE name = 'Kalisz';
UPDATE marketing_cities SET population = 98436 WHERE name = 'Legnica';
UPDATE marketing_cities SET population = 93564 WHERE name = 'Grudziądz';
UPDATE marketing_cities SET population = 90368 WHERE name = 'Jaworzno';
UPDATE marketing_cities SET population = 89780 WHERE name = 'Słupsk';
UPDATE marketing_cities SET population = 88038 WHERE name = 'Jastrzębie-Zdrój';
UPDATE marketing_cities SET population = 83558 WHERE name = 'Nowy Sącz';
UPDATE marketing_cities SET population = 78335 WHERE name = 'Jelenia Góra';
UPDATE marketing_cities SET population = 77813 WHERE name = 'Siedlce';
UPDATE marketing_cities SET population = 74559 WHERE name = 'Mysłowice';
UPDATE marketing_cities SET population = 72539 WHERE name = 'Konin';
UPDATE marketing_cities SET population = 72527 WHERE name = 'Piła';
UPDATE marketing_cities SET population = 72250 WHERE name = 'Piotrków Trybunalski';
UPDATE marketing_cities SET population = 71710 WHERE name = 'Lubin';
UPDATE marketing_cities SET population = 71674 WHERE name = 'Inowrocław';
UPDATE marketing_cities SET population = 71560 WHERE name = 'Ostrów Wielkopolski';
UPDATE marketing_cities SET population = 69639 WHERE name = 'Suwałki';
UPDATE marketing_cities SET population = 67579 WHERE name = 'Stargard';
UPDATE marketing_cities SET population = 67570 WHERE name = 'Gniezno';
UPDATE marketing_cities SET population = 67404 WHERE name = 'Ostrowiec Świętokrzyski';
UPDATE marketing_cities SET population = 66270 WHERE name = 'Siemianowice Śląskie';
UPDATE marketing_cities SET population = 66120 WHERE name = 'Głogów';
UPDATE marketing_cities SET population = 63945 WHERE name = 'Pabianice';
UPDATE marketing_cities SET population = 62854 WHERE name = 'Leszno';
UPDATE marketing_cities SET population = 62844 WHERE name = 'Żory';
UPDATE marketing_cities SET population = 62785 WHERE name = 'Zamość';
UPDATE marketing_cities SET population = 62623 WHERE name = 'Pruszków';
UPDATE marketing_cities SET population = 62573 WHERE name = 'Łomża';
UPDATE marketing_cities SET population = 61903 WHERE name = 'Ełk';
UPDATE marketing_cities SET population = 61756 WHERE name = 'Tarnowskie Góry';
UPDATE marketing_cities SET population = 61338 WHERE name = 'Tomaszów Mazowiecki';
UPDATE marketing_cities SET population = 61135 WHERE name = 'Chełm';
UPDATE marketing_cities SET population = 60075 WHERE name = 'Mielec';
UPDATE marketing_cities SET population = 60021 WHERE name = 'Kędzierzyn-Koźle';
UPDATE marketing_cities SET population = 59779 WHERE name = 'Przemyśl';
UPDATE marketing_cities SET population = 59623 WHERE name = 'Stalowa Wola';
UPDATE marketing_cities SET population = 59430 WHERE name = 'Tczew';
UPDATE marketing_cities SET population = 56942 WHERE name = 'Biała Podlaska';
UPDATE marketing_cities SET population = 56419 WHERE name = 'Bełchatów';
UPDATE marketing_cities SET population = 56222 WHERE name = 'Świdnica';
UPDATE marketing_cities SET population = 56008 WHERE name = 'Będzin';
UPDATE marketing_cities SET population = 55673 WHERE name = 'Zgierz';
UPDATE marketing_cities SET population = 54702 WHERE name = 'Piekary Śląskie';
UPDATE marketing_cities SET population = 54259 WHERE name = 'Racibórz';
UPDATE marketing_cities SET population = 53529 WHERE name = 'Legionowo';
UPDATE marketing_cities SET population = 51656 WHERE name = 'Ostrołęka';
UPDATE marketing_cities SET population = 49536 WHERE name = 'Rumia';
UPDATE marketing_cities SET population = 49108 WHERE name = 'Świętochłowice';
UPDATE marketing_cities SET population = 49099 WHERE name = 'Wejherowo';
UPDATE marketing_cities SET population = 48703 WHERE name = 'Zawiercie';
UPDATE marketing_cities SET population = 48670 WHERE name = 'Piaseczno';
UPDATE marketing_cities SET population = 47655 WHERE name = 'Skierniewice';
UPDATE marketing_cities SET population = 47638 WHERE name = 'Starachowice';
UPDATE marketing_cities SET population = 47576 WHERE name = 'Wodzisław Śląski';
UPDATE marketing_cities SET population = 47272 WHERE name = 'Starogard Gdański';
UPDATE marketing_cities SET population = 46965 WHERE name = 'Puławy';
UPDATE marketing_cities SET population = 46360 WHERE name = 'Tarnobrzeg';
UPDATE marketing_cities SET population = 46198 WHERE name = 'Kołobrzeg';
UPDATE marketing_cities SET population = 45948 WHERE name = 'Krosno';
UPDATE marketing_cities SET population = 45353 WHERE name = 'Radomsko';
UPDATE marketing_cities SET population = 45189 WHERE name = 'Dębica';
UPDATE marketing_cities SET population = 44317 WHERE name = 'Otwock';
UPDATE marketing_cities SET population = 44260 WHERE name = 'Skarżysko-Kamienna';
UPDATE marketing_cities SET population = 43883 WHERE name = 'Ciechanów';
UPDATE marketing_cities SET population = 43356 WHERE name = 'Nysa';
UPDATE marketing_cities SET population = 43332 WHERE name = 'Kutno';
UPDATE marketing_cities SET population = 41390 WHERE name = 'Sieradz';
UPDATE marketing_cities SET population = 41288 WHERE name = 'Zduńska Wola';
UPDATE marketing_cities SET population = 41003 WHERE name = 'Mikołów';
UPDATE marketing_cities SET population = 40948 WHERE name = 'Świnoujście';
UPDATE marketing_cities SET population = 40916 WHERE name = 'Mińsk Mazowiecki';
UPDATE marketing_cities SET population = 39827 WHERE name = 'Szczecinek';
UPDATE marketing_cities SET population = 39647 WHERE name = 'Chojnice';
UPDATE marketing_cities SET population = 39550 WHERE name = 'Żyrardów';
UPDATE marketing_cities SET population = 38763 WHERE name = 'Świdnik';
UPDATE marketing_cities SET population = 38546 WHERE name = 'Ząbki';
UPDATE marketing_cities SET population = 38486 WHERE name = 'Bolesławiec';
UPDATE marketing_cities SET population = 38329 WHERE name = 'Kwidzyn';
UPDATE marketing_cities SET population = 38191 WHERE name = 'Nowa Sól';
UPDATE marketing_cities SET population = 38101 WHERE name = 'Malbork';
UPDATE marketing_cities SET population = 37801 WHERE name = 'Knurów';
UPDATE marketing_cities SET population = 37569 WHERE name = 'Oświęcim';
UPDATE marketing_cities SET population = 37073 WHERE name = 'Jarosław';
UPDATE marketing_cities SET population = 37052 WHERE name = 'Żary';
UPDATE marketing_cities SET population = 36999 WHERE name = 'Sanok';
UPDATE marketing_cities SET population = 36979 WHERE name = 'Oleśnica';
UPDATE marketing_cities SET population = 36848 WHERE name = 'Wołomin';
UPDATE marketing_cities SET population = 36816 WHERE name = 'Marki';
UPDATE marketing_cities SET population = 36118 WHERE name = 'Chrzanów';
UPDATE marketing_cities SET population = 35891 WHERE name = 'Sochaczew';
UPDATE marketing_cities SET population = 35839 WHERE name = 'Czechowice-Dziedzice';
UPDATE marketing_cities SET population = 35286 WHERE name = 'Sopot';
UPDATE marketing_cities SET population = 35226 WHERE name = 'Brzeg';
UPDATE marketing_cities SET population = 35101 WHERE name = 'Lębork';
UPDATE marketing_cities SET population = 34757 WHERE name = 'Olkusz';
UPDATE marketing_cities SET population = 34542 WHERE name = 'Jasło';
UPDATE marketing_cities SET population = 33981 WHERE name = 'Cieszyn';
UPDATE marketing_cities SET population = 33917 WHERE name = 'Kraśnik';
UPDATE marketing_cities SET population = 33257 WHERE name = 'Nowy Targ';
UPDATE marketing_cities SET population = 33206 WHERE name = 'Iława';
UPDATE marketing_cities SET population = 33087 WHERE name = 'Oława';
UPDATE marketing_cities SET population = 32869 WHERE name = 'Dzierżoniów';
UPDATE marketing_cities SET population = 32714 WHERE name = 'Ostróda';
UPDATE marketing_cities SET population = 32452 WHERE name = 'Grodzisk Mazowiecki';
UPDATE marketing_cities SET population = 32243 WHERE name = 'Police';
UPDATE marketing_cities SET population = 32015 WHERE name = 'Luboń';
UPDATE marketing_cities SET population = 31578 WHERE name = 'Pruszcz Gdański';
UPDATE marketing_cities SET population = 31261 WHERE name = 'Myszków';
UPDATE marketing_cities SET population = 31129 WHERE name = 'Mława';
UPDATE marketing_cities SET population = 31039 WHERE name = 'Czeladź';
UPDATE marketing_cities SET population = 31000 WHERE name = 'Września';
UPDATE marketing_cities SET population = 30733 WHERE name = 'Żywiec';
UPDATE marketing_cities SET population = 29946 WHERE name = 'Augustów';
UPDATE marketing_cities SET population = 29862 WHERE name = 'Swarzędz';
UPDATE marketing_cities SET population = 29810 WHERE name = 'Zgorzelec';
UPDATE marketing_cities SET population = 29554 WHERE name = 'Bochnia';
UPDATE marketing_cities SET population = 29523 WHERE name = 'Bielawa';
UPDATE marketing_cities SET population = 29441 WHERE name = 'Łuków';
UPDATE marketing_cities SET population = 29176 WHERE name = 'Śrem';
UPDATE marketing_cities SET population = 28964 WHERE name = 'Giżycko';
UPDATE marketing_cities SET population = 28701 WHERE name = 'Brodnica';
UPDATE marketing_cities SET population = 28701 WHERE name = 'Krotoszyn';
UPDATE marketing_cities SET population = 28691 WHERE name = 'Nowy Dwór Mazowiecki';
UPDATE marketing_cities SET population = 27896 WHERE name = 'Łowicz';
UPDATE marketing_cities SET population = 27888 WHERE name = 'Czerwionka-Leszczyny';
UPDATE marketing_cities SET population = 26980 WHERE name = 'Wyszków';
UPDATE marketing_cities SET population = 26973 WHERE name = 'Gorlice';
UPDATE marketing_cities SET population = 26846 WHERE name = 'Zakopane';
UPDATE marketing_cities SET population = 26788 WHERE name = 'Kętrzyn';
UPDATE marketing_cities SET population = 26707 WHERE name = 'Reda';
UPDATE marketing_cities SET population = 26453 WHERE name = 'Jarocin';
UPDATE marketing_cities SET population = 26441 WHERE name = 'Turek';
UPDATE marketing_cities SET population = 26421 WHERE name = 'Kłodzko';
UPDATE marketing_cities SET population = 26114 WHERE name = 'Biłgoraj';
UPDATE marketing_cities SET population = 25702 WHERE name = 'Pszczyna';
UPDATE marketing_cities SET population = 25607 WHERE name = 'Wągrowiec';
UPDATE marketing_cities SET population = 25486 WHERE name = 'Świecie';
UPDATE marketing_cities SET population = 25265 WHERE name = 'Żagań';
UPDATE marketing_cities SET population = 25149 WHERE name = 'Kobyłka';
UPDATE marketing_cities SET population = 25044 WHERE name = 'Bielsk Podlaski';
UPDATE marketing_cities SET population = 24949 WHERE name = 'Wałcz';
UPDATE marketing_cities SET population = 24366 WHERE name = 'Skawina';
UPDATE marketing_cities SET population = 24215 WHERE name = 'Wieliczka';
UPDATE marketing_cities SET population = 23950 WHERE name = 'Białogard';
UPDATE marketing_cities SET population = 23778 WHERE name = 'Kościerzyna';
UPDATE marketing_cities SET population = 23716 WHERE name = 'Kościan';
UPDATE marketing_cities SET population = 23672 WHERE name = 'Środa Wielkopolska';
UPDATE marketing_cities SET population = 23551 WHERE name = 'Lubliniec';
UPDATE marketing_cities SET population = 23254 WHERE name = 'Kluczbork';
UPDATE marketing_cities SET population = 22997 WHERE name = 'Sandomierz';
UPDATE marketing_cities SET population = 22984 WHERE name = 'Bartoszyce';
UPDATE marketing_cities SET population = 22813 WHERE name = 'Szczytno';
UPDATE marketing_cities SET population = 22642 WHERE name = 'Świebodzice';
UPDATE marketing_cities SET population = 22559 WHERE name = 'Piastów';
UPDATE marketing_cities SET population = 22462 WHERE name = 'Jawor';
UPDATE marketing_cities SET population = 22435 WHERE name = 'Polkowice';
UPDATE marketing_cities SET population = 22216 WHERE name = 'Ostrów Mazowiecka';
UPDATE marketing_cities SET population = 22130 WHERE name = 'Łaziska Górne';
UPDATE marketing_cities SET population = 21979 WHERE name = 'Goleniów';
UPDATE marketing_cities SET population = 21924 WHERE name = 'Płońsk';
UPDATE marketing_cities SET population = 21921 WHERE name = 'Zambrów';
UPDATE marketing_cities SET population = 21892 WHERE name = 'Wieluń';
UPDATE marketing_cities SET population = 21754 WHERE name = 'Aleksandrów Łódzki';
UPDATE marketing_cities SET population = 21709 WHERE name = 'Grajewo';
UPDATE marketing_cities SET population = 21643 WHERE name = 'Nowa Ruda';
UPDATE marketing_cities SET population = 21636 WHERE name = 'Lubartów';
UPDATE marketing_cities SET population = 21550 WHERE name = 'Świebodzin';
UPDATE marketing_cities SET population = 21385 WHERE name = 'Rydułtowy';
UPDATE marketing_cities SET population = 21302 WHERE name = 'Mrągowo';
UPDATE marketing_cities SET population = 21290 WHERE name = 'Orzesze';
UPDATE marketing_cities SET population = 21247 WHERE name = 'Koło';
UPDATE marketing_cities SET population = 21145 WHERE name = 'Działdowo';
UPDATE marketing_cities SET population = 20923 WHERE name = 'Gryfino';
UPDATE marketing_cities SET population = 20746 WHERE name = 'Opoczno';
UPDATE marketing_cities SET population = 20741 WHERE name = 'Józefów';
UPDATE marketing_cities SET population = 20723 WHERE name = 'Lubań';
UPDATE marketing_cities SET population = 20671 WHERE name = 'Prudnik';
UPDATE marketing_cities SET population = 20265 WHERE name = 'Hajnówka';
UPDATE marketing_cities SET population = 20250 WHERE name = 'Gostyń';
UPDATE marketing_cities SET population = 20187 WHERE name = 'Rawicz';
UPDATE marketing_cities SET population = 19951 WHERE name = 'Sulejówek';
UPDATE marketing_cities SET population = 19837 WHERE name = 'Andrychów';
UPDATE marketing_cities SET population = 19507 WHERE name = 'Trzebinia';
UPDATE marketing_cities SET population = 19375 WHERE name = 'Bieruń';
UPDATE marketing_cities SET population = 19294 WHERE name = 'Pułtusk';
UPDATE marketing_cities SET population = 19205 WHERE name = 'Chełmno';
UPDATE marketing_cities SET population = 19128 WHERE name = 'Ozorków';
UPDATE marketing_cities SET population = 19029 WHERE name = 'Pisz';
UPDATE marketing_cities SET population = 18878 WHERE name = 'Końskie';
UPDATE marketing_cities SET population = 18814 WHERE name = 'Sokołów Podlaski';
UPDATE marketing_cities SET population = 18783 WHERE name = 'Tomaszów Lubelski';
UPDATE marketing_cities SET population = 18736 WHERE name = 'Szamotuły';
UPDATE marketing_cities SET population = 18675 WHERE name = 'Łęczna';
UPDATE marketing_cities SET population = 18585 WHERE name = 'Kamienna Góra';
UPDATE marketing_cities SET population = 18455 WHERE name = 'Pyskowice';
UPDATE marketing_cities SET population = 18443 WHERE name = 'Kęty';
UPDATE marketing_cities SET population = 18437 WHERE name = 'Złotów';
UPDATE marketing_cities SET population = 18383 WHERE name = 'Krasnystaw';
UPDATE marketing_cities SET population = 18379 WHERE name = 'Wadowice';
UPDATE marketing_cities SET population = 18355 WHERE name = 'Gostynin';
UPDATE marketing_cities SET population = 18335 WHERE name = 'Konstantynów Łódzki';
UPDATE marketing_cities SET population = 18325 WHERE name = 'Myślenice';
UPDATE marketing_cities SET population = 18229 WHERE name = 'Chodzież';
UPDATE marketing_cities SET population = 18026 WHERE name = 'Nakło nad Notecią';
UPDATE marketing_cities SET population = 17967 WHERE name = 'Sokółka';
UPDATE marketing_cities SET population = 17902 WHERE name = 'Pionki';
UPDATE marketing_cities SET population = 17848 WHERE name = 'Oborniki';
UPDATE marketing_cities SET population = 17788 WHERE name = 'Sierpc';
UPDATE marketing_cities SET population = 17704 WHERE name = 'Kostrzyn nad Odrą';
UPDATE marketing_cities SET population = 17675 WHERE name = 'Łańcut';
UPDATE marketing_cities SET population = 17667 WHERE name = 'Międzyrzecz';
UPDATE marketing_cities SET population = 17665 WHERE name = 'Radlin';
UPDATE marketing_cities SET population = 17657 WHERE name = 'Strzelce Opolskie';
UPDATE marketing_cities SET population = 17548 WHERE name = 'Garwolin';
UPDATE marketing_cities SET population = 17486 WHERE name = 'Zielonka';
UPDATE marketing_cities SET population = 17232 WHERE name = 'Hrubieszów';
UPDATE marketing_cities SET population = 17193 WHERE name = 'Rawa Mazowiecka';
UPDATE marketing_cities SET population = 17080 WHERE name = 'Łomianki';
UPDATE marketing_cities SET population = 17055 WHERE name = 'Przasnysz';
UPDATE marketing_cities SET population = 17037 WHERE name = 'Bogatynia';
UPDATE marketing_cities SET population = 17009 WHERE name = 'Trzcianka';
UPDATE marketing_cities SET population = 16974 WHERE name = 'Braniewo';
UPDATE marketing_cities SET population = 16953 WHERE name = 'Pleszew';
UPDATE marketing_cities SET population = 16925 WHERE name = 'Łask';
UPDATE marketing_cities SET population = 16903 WHERE name = 'Radzionków';
UPDATE marketing_cities SET population = 16889 WHERE name = 'Konstancin-Jeziorna';
UPDATE marketing_cities SET population = 16877 WHERE name = 'Kozienice';
UPDATE marketing_cities SET population = 16838 WHERE name = 'Libiąż';
UPDATE marketing_cities SET population = 16833 WHERE name = 'Bytów';
UPDATE marketing_cities SET population = 16785 WHERE name = 'Grójec';
UPDATE marketing_cities SET population = 16764 WHERE name = 'Brzesko';
UPDATE marketing_cities SET population = 16731 WHERE name = 'Lędziny';
UPDATE marketing_cities SET population = 16667 WHERE name = 'Międzyrzec Podlaski';
UPDATE marketing_cities SET population = 16623 WHERE name = 'Słubice';
UPDATE marketing_cities SET population = 16622 WHERE name = 'Namysłów';
UPDATE marketing_cities SET population = 16592 WHERE name = 'Sulechów';
UPDATE marketing_cities SET population = 16528 WHERE name = 'Gubin';
UPDATE marketing_cities SET population = 16478 WHERE name = 'Milanówek';
UPDATE marketing_cities SET population = 16448 WHERE name = 'Nowogard';
UPDATE marketing_cities SET population = 16364 WHERE name = 'Olecko';
UPDATE marketing_cities SET population = 16212 WHERE name = 'Gryfice';
UPDATE marketing_cities SET population = 15999 WHERE name = 'Rypin';
UPDATE marketing_cities SET population = 15989 WHERE name = 'Ustroń';
UPDATE marketing_cities SET population = 15962 WHERE name = 'Krapkowice';
UPDATE marketing_cities SET population = 15887 WHERE name = 'Dęblin';
UPDATE marketing_cities SET population = 15873 WHERE name = 'Strzegom';
UPDATE marketing_cities SET population = 15864 WHERE name = 'Ropczyce';
UPDATE marketing_cities SET population = 15648 WHERE name = 'Jelcz-Laskowice';
UPDATE marketing_cities SET population = 15614 WHERE name = 'Solec Kujawski';
UPDATE marketing_cities SET population = 15611 WHERE name = 'Busko-Zdrój';
UPDATE marketing_cities SET population = 15489 WHERE name = 'Lidzbark Warmiński';
UPDATE marketing_cities SET population = 15428 WHERE name = 'Radzyń Podlaski';
UPDATE marketing_cities SET population = 15412 WHERE name = 'Łapy';
UPDATE marketing_cities SET population = 15338 WHERE name = 'Świdwin';
UPDATE marketing_cities SET population = 15273 WHERE name = 'Złotoryja';
UPDATE marketing_cities SET population = 15199 WHERE name = 'Ustka';
UPDATE marketing_cities SET population = 15193 WHERE name = 'Nisko';
UPDATE marketing_cities SET population = 15154 WHERE name = 'Boguszów-Gorce';
UPDATE marketing_cities SET population = 15105 WHERE name = 'Przeworsk';
UPDATE marketing_cities SET population = 15067 WHERE name = 'Limanowa';
UPDATE marketing_cities SET population = 14998 WHERE name = 'Choszczno';
UPDATE marketing_cities SET population = 14812 WHERE name = 'Jędrzejów';
UPDATE marketing_cities SET population = 14728 WHERE name = 'Ząbkowice Śląskie';
UPDATE marketing_cities SET population = 14713 WHERE name = 'Grodzisk Wielkopolski';
UPDATE marketing_cities SET population = 14534 WHERE name = 'Staszów';
UPDATE marketing_cities SET population = 14362 WHERE name = 'Chełmża';
UPDATE marketing_cities SET population = 14319 WHERE name = 'Nowy Tomyśl';
UPDATE marketing_cities SET population = 14283 WHERE name = 'Lipno';
UPDATE marketing_cities SET population = 14276 WHERE name = 'Kartuzy';
UPDATE marketing_cities SET population = 14255 WHERE name = 'Mosina';
UPDATE marketing_cities SET population = 14210 WHERE name = 'Siemiatycze';
UPDATE marketing_cities SET population = 14116 WHERE name = 'Skoczów';
UPDATE marketing_cities SET population = 14022 WHERE name = 'Niepołomice';
UPDATE marketing_cities SET population = 13964 WHERE name = 'Ostrzeszów';
UPDATE marketing_cities SET population = 13961 WHERE name = 'Głowno';
UPDATE marketing_cities SET population = 13889 WHERE name = 'Kępno';
UPDATE marketing_cities SET population = 13786 WHERE name = 'Łęczyca';
UPDATE marketing_cities SET population = 13734 WHERE name = 'Pszów';
UPDATE marketing_cities SET population = 13733 WHERE name = 'Lubsko';
UPDATE marketing_cities SET population = 13717 WHERE name = 'Wschowa';
UPDATE marketing_cities SET population = 13710 WHERE name = 'Brwinów';
UPDATE marketing_cities SET population = 13626 WHERE name = 'Dębno';
UPDATE marketing_cities SET population = 13623 WHERE name = 'Żnin';
UPDATE marketing_cities SET population = 13611 WHERE name = 'Barlinek';
UPDATE marketing_cities SET population = 13600 WHERE name = 'Gołdap';
UPDATE marketing_cities SET population = 13585 WHERE name = 'Leżajsk';
UPDATE marketing_cities SET population = 13574 WHERE name = 'Darłowo';
UPDATE marketing_cities SET population = 13564 WHERE name = 'Słupca';
UPDATE marketing_cities SET population = 13547 WHERE name = 'Nidzica';
UPDATE marketing_cities SET population = 13534 WHERE name = 'Tuchola';
UPDATE marketing_cities SET population = 13479 WHERE name = 'Człuchów';
UPDATE marketing_cities SET population = 13459 WHERE name = 'Morąg';
UPDATE marketing_cities SET population = 13400 WHERE name = 'Wąbrzeźno';
UPDATE marketing_cities SET population = 13388 WHERE name = 'Głuchołazy';
UPDATE marketing_cities SET population = 13314 WHERE name = 'Trzebnica';
UPDATE marketing_cities SET population = 13313 WHERE name = 'Radzymin';
UPDATE marketing_cities SET population = 13236 WHERE name = 'Chojnów';
UPDATE marketing_cities SET population = 12915 WHERE name = 'Włodawa';
UPDATE marketing_cities SET population = 12859 WHERE name = 'Wolsztyn';
UPDATE marketing_cities SET population = 12776 WHERE name = 'Koluszki';
UPDATE marketing_cities SET population = 12756 WHERE name = 'Kłobuck';
UPDATE marketing_cities SET population = 12706 WHERE name = 'Złocieniec';
UPDATE marketing_cities SET population = 12662 WHERE name = 'Rabka-Zdrój';
UPDATE marketing_cities SET population = 12484 WHERE name = 'Pyrzyce';
UPDATE marketing_cities SET population = 12480 WHERE name = 'Brzeg Dolny';
UPDATE marketing_cities SET population = 12452 WHERE name = 'Węgrów';
UPDATE marketing_cities SET population = 12441 WHERE name = 'Głubczyce';
UPDATE marketing_cities SET population = 12432 WHERE name = 'Ożarów Mazowiecki';
UPDATE marketing_cities SET population = 12415 WHERE name = 'Sędziszów Małopolski';
UPDATE marketing_cities SET population = 12412 WHERE name = 'Golub-Dobrzyń';
UPDATE marketing_cities SET population = 12383 WHERE name = 'Strzelin';
UPDATE marketing_cities SET population = 12365 WHERE name = 'Brzeziny';
UPDATE marketing_cities SET population = 12357 WHERE name = 'Sławno';
UPDATE marketing_cities SET population = 12298 WHERE name = 'Wołów';
UPDATE marketing_cities SET population = 12134 WHERE name = 'Błonie';
UPDATE marketing_cities SET population = 12117 WHERE name = 'Pasłęk';
UPDATE marketing_cities SET population = 12058 WHERE name = 'Aleksandrów Kujawski';
UPDATE marketing_cities SET population = 11988 WHERE name = 'Góra Kalwaria';
UPDATE marketing_cities SET population = 11926 WHERE name = 'Warka';
UPDATE marketing_cities SET population = 11844 WHERE name = 'Dąbrowa Tarnowska';
UPDATE marketing_cities SET population = 11830 WHERE name = 'Lubaczów';
UPDATE marketing_cities SET population = 11802 WHERE name = 'Wasilków';
UPDATE marketing_cities SET population = 11661 WHERE name = 'Janów Lubelski';
UPDATE marketing_cities SET population = 11652 WHERE name = 'Mogilno';
UPDATE marketing_cities SET population = 11574 WHERE name = 'Góra';
UPDATE marketing_cities SET population = 11557 WHERE name = 'Szydłowiec';
UPDATE marketing_cities SET population = 11530 WHERE name = 'Szprotawa';
UPDATE marketing_cities SET population = 11500 WHERE name = 'Miechów';
UPDATE marketing_cities SET population = 11417 WHERE name = 'Drawsko Pomorskie';
UPDATE marketing_cities SET population = 11246 WHERE name = 'Zdzieszowice';
UPDATE marketing_cities SET population = 11199 WHERE name = 'Milicz';
UPDATE marketing_cities SET population = 11155 WHERE name = 'Krosno Odrzańskie';
UPDATE marketing_cities SET population = 11144 WHERE name = 'Węgorzewo';
UPDATE marketing_cities SET population = 11139 WHERE name = 'Puck';
UPDATE marketing_cities SET population = 11124 WHERE name = 'Rogoźno';
UPDATE marketing_cities SET population = 11092 WHERE name = 'Brzeszcze';
UPDATE marketing_cities SET population = 11070 WHERE name = 'Koronowo';
UPDATE marketing_cities SET population = 11064 WHERE name = 'Wronki';
UPDATE marketing_cities SET population = 11049 WHERE name = 'Myślibórz';
UPDATE marketing_cities SET population = 11007 WHERE name = 'Wisła';
UPDATE marketing_cities SET population = 11006 WHERE name = 'Nowa Dęba';
UPDATE marketing_cities SET population = 10709 WHERE name = 'Nowe Miasto Lubawskie';
UPDATE marketing_cities SET population = 10650 WHERE name = 'Kowary';
UPDATE marketing_cities SET population = 10628 WHERE name = 'Biskupiec';
UPDATE marketing_cities SET population = 10555 WHERE name = 'Parczew';
UPDATE marketing_cities SET population = 10534 WHERE name = 'Ciechocinek';
UPDATE marketing_cities SET population = 10524 WHERE name = 'Pińczów';
UPDATE marketing_cities SET population = 10476 WHERE name = 'Międzychód';
UPDATE marketing_cities SET population = 10464 WHERE name = 'Czarnków';
UPDATE marketing_cities SET population = 10456 WHERE name = 'Krynica-Zdrój';
UPDATE marketing_cities SET population = 10410 WHERE name = 'Murowana Goślina';
UPDATE marketing_cities SET population = 10374 WHERE name = 'Lubawa';
UPDATE marketing_cities SET population = 10340 WHERE name = 'Syców';
UPDATE marketing_cities SET population = 10211 WHERE name = 'Miastko';
UPDATE marketing_cities SET population = 10143 WHERE name = 'Kolno';
UPDATE marketing_cities SET population = 10048 WHERE name = 'Łobez';
UPDATE marketing_cities SET population = 10010 WHERE name = 'Dobre Miasto';
UPDATE marketing_cities SET population = 10005 WHERE name = 'Sulęcin';
UPDATE marketing_cities SET population = 9978 WHERE name = 'Drezdenko';
UPDATE marketing_cities SET population = 9976 WHERE name = 'Bukowno';
UPDATE marketing_cities SET population = 9969 WHERE name = 'Krzeszowice';
UPDATE marketing_cities SET population = 9933 WHERE name = 'Mońki';
UPDATE marketing_cities SET population = 9900 WHERE name = 'Czersk';
UPDATE marketing_cities SET population = 9899 WHERE name = 'Trzebiatów';
UPDATE marketing_cities SET population = 9878 WHERE name = 'Bystrzyca Kłodzka';
UPDATE marketing_cities SET population = 9862 WHERE name = 'Nowy Dwór Gdański';
UPDATE marketing_cities SET population = 9833 WHERE name = 'Strzelce Krajeńskie';
UPDATE marketing_cities SET population = 9830 WHERE name = 'Władysławowo';
UPDATE marketing_cities SET population = 9811 WHERE name = 'Karczew';
UPDATE marketing_cities SET population = 9800 WHERE name = 'Głogów Małopolski';
UPDATE marketing_cities SET population = 9798 WHERE name = 'Sztum';
UPDATE marketing_cities SET population = 9798 WHERE name = 'Włoszczowa';
UPDATE marketing_cities SET population = 9772 WHERE name = 'Kudowa-Zdrój';
UPDATE marketing_cities SET population = 9697 WHERE name = 'Kostrzyn';
UPDATE marketing_cities SET population = 9578 WHERE name = 'Szubin';
UPDATE marketing_cities SET population = 9575 WHERE name = 'Maków Mazowiecki';
UPDATE marketing_cities SET population = 9575 WHERE name = 'Puszczykowo';
UPDATE marketing_cities SET population = 9562 WHERE name = 'Środa Śląska';
UPDATE marketing_cities SET population = 9545 WHERE name = 'Opalenica';
UPDATE marketing_cities SET population = 9531 WHERE name = 'Ryki';
UPDATE marketing_cities SET population = 9457 WHERE name = 'Blachownia';
UPDATE marketing_cities SET population = 9454 WHERE name = 'Skwierzyna';
UPDATE marketing_cities SET population = 9451 WHERE name = 'Pobiedziska';
UPDATE marketing_cities SET population = 9353 WHERE name = 'Olesno';
UPDATE marketing_cities SET population = 9337 WHERE name = 'Kożuchów';
UPDATE marketing_cities SET population = 9336 WHERE name = 'Wysokie Mazowieckie';
UPDATE marketing_cities SET population = 9331 WHERE name = 'Kruszwica';
UPDATE marketing_cities SET population = 9269 WHERE name = 'Imielin';
UPDATE marketing_cities SET population = 9198 WHERE name = 'Czarna Białostocka';
UPDATE marketing_cities SET population = 9075 WHERE name = 'Oborniki Śląskie';
UPDATE marketing_cities SET population = 9044 WHERE name = 'Sucha Beskidzka';
UPDATE marketing_cities SET population = 9016 WHERE name = 'Stary Sącz';
UPDATE marketing_cities SET population = 9004 WHERE name = 'Sępólno Krajeńskie';
UPDATE marketing_cities SET population = 8980 WHERE name = 'Poniatowa';
UPDATE marketing_cities SET population = 8922 WHERE name = 'Kolbuszowa';
UPDATE marketing_cities SET population = 8917 WHERE name = 'Ustrzyki Dolne';
UPDATE marketing_cities SET population = 8912 WHERE name = 'Chełmek';
UPDATE marketing_cities SET population = 8877 WHERE name = 'Wojkowice';
UPDATE marketing_cities SET population = 8851 WHERE name = 'Siechnice';
UPDATE marketing_cities SET population = 8781 WHERE name = 'Strzyżów';
UPDATE marketing_cities SET population = 8756 WHERE name = 'Żuromin';
UPDATE marketing_cities SET population = 8753 WHERE name = 'Lwówek Śląski';
UPDATE marketing_cities SET population = 8677 WHERE name = 'Kamień Pomorski';
UPDATE marketing_cities SET population = 8648 WHERE name = 'Orneta';
UPDATE marketing_cities SET population = 8638 WHERE name = 'Janikowo';
UPDATE marketing_cities SET population = 8625 WHERE name = 'Prabuty';
UPDATE marketing_cities SET population = 8580 WHERE name = 'Jastrowie';
UPDATE marketing_cities SET population = 8548 WHERE name = 'Kalety';
UPDATE marketing_cities SET population = 8531 WHERE name = 'Ziębice';
UPDATE marketing_cities SET population = 8501 WHERE name = 'Grodków';
UPDATE marketing_cities SET population = 8480 WHERE name = 'Ozimek';
UPDATE marketing_cities SET population = 8480 WHERE name = 'Wolbrom';
UPDATE marketing_cities SET population = 8461 WHERE name = 'Poręba';
UPDATE marketing_cities SET population = 8446 WHERE name = 'Wieruszów';
UPDATE marketing_cities SET population = 8320 WHERE name = 'Opole Lubelskie';
UPDATE marketing_cities SET population = 8248 WHERE name = 'Suchedniów';
UPDATE marketing_cities SET population = 8167 WHERE name = 'Tłuszcz';
UPDATE marketing_cities SET population = 8135 WHERE name = 'Żukowo';
UPDATE marketing_cities SET population = 8084 WHERE name = 'Pniewy';
UPDATE marketing_cities SET population = 8023 WHERE name = 'Kórnik';
UPDATE marketing_cities SET population = 7988 WHERE name = 'Połaniec';
UPDATE marketing_cities SET population = 7987 WHERE name = 'Połczyn-Zdrój';
UPDATE marketing_cities SET population = 7964 WHERE name = 'Żychlin';
UPDATE marketing_cities SET population = 7899 WHERE name = 'Mszana Dolna';
UPDATE marketing_cities SET population = 7773 WHERE name = 'Chocianów';
UPDATE marketing_cities SET population = 7706 WHERE name = 'Witkowo';
UPDATE marketing_cities SET population = 7660 WHERE name = 'Zwoleń';
UPDATE marketing_cities SET population = 7650 WHERE name = 'Nasielsk';
UPDATE marketing_cities SET population = 7635 WHERE name = 'Lidzbark';
UPDATE marketing_cities SET population = 7606 WHERE name = 'Trzemeszno';
UPDATE marketing_cities SET population = 7597 WHERE name = 'Pelplin';
UPDATE marketing_cities SET population = 7515 WHERE name = 'Praszka';
UPDATE marketing_cities SET population = 7509 WHERE name = 'Barczewo';
UPDATE marketing_cities SET population = 7491 WHERE name = 'Olsztynek';
UPDATE marketing_cities SET population = 7459 WHERE name = 'Zelów';
UPDATE marketing_cities SET population = 7425 WHERE name = 'Brzozów';
UPDATE marketing_cities SET population = 7418 WHERE name = 'Miasteczko Śląskie';
UPDATE marketing_cities SET population = 7367 WHERE name = 'Chojna';
UPDATE marketing_cities SET population = 7366 WHERE name = 'Paczków';
UPDATE marketing_cities SET population = 7313 WHERE name = 'Barcin';
UPDATE marketing_cities SET population = 7245 WHERE name = 'Poddębice';
UPDATE marketing_cities SET population = 7237 WHERE name = 'Tuszyn';
UPDATE marketing_cities SET population = 7213 WHERE name = 'Zbąszyń';
UPDATE marketing_cities SET population = 7094 WHERE name = 'Czaplinek';
UPDATE marketing_cities SET population = 7060 WHERE name = 'Gniewkowo';
UPDATE marketing_cities SET population = 7032 WHERE name = 'Zawadzkie';
UPDATE marketing_cities SET population = 7028 WHERE name = 'Kąty Wrocławskie';
UPDATE marketing_cities SET population = 7023 WHERE name = 'Łosice';
UPDATE marketing_cities SET population = 7015 WHERE name = 'Skarszewy';
UPDATE marketing_cities SET population = 7012 WHERE name = 'Pieszyce';
UPDATE marketing_cities SET population = 6954 WHERE name = 'Sobótka';
UPDATE marketing_cities SET population = 6935 WHERE name = 'Sławków';
UPDATE marketing_cities SET population = 6853 WHERE name = 'Białobrzegi';
UPDATE marketing_cities SET population = 6822 WHERE name = 'Łochów';
UPDATE marketing_cities SET population = 6765 WHERE name = 'Gogolin';
UPDATE marketing_cities SET population = 6744 WHERE name = 'Łazy';
UPDATE marketing_cities SET population = 6677 WHERE name = 'Rudnik nad Sanem';
UPDATE marketing_cities SET population = 6666 WHERE name = 'Witnica';
UPDATE marketing_cities SET population = 6658 WHERE name = 'Sułkowice';
UPDATE marketing_cities SET population = 6653 WHERE name = 'Szklarska Poręba';
UPDATE marketing_cities SET population = 6651 WHERE name = 'Pajęczno';
UPDATE marketing_cities SET population = 6648 WHERE name = 'Żarów';
UPDATE marketing_cities SET population = 6608 WHERE name = 'Gniew';
UPDATE marketing_cities SET population = 6597 WHERE name = 'Twardogóra';
UPDATE marketing_cities SET population = 6560 WHERE name = 'Sianów';
UPDATE marketing_cities SET population = 6510 WHERE name = 'Tuchów';
UPDATE marketing_cities SET population = 6509 WHERE name = 'Gryfów Śląski';
UPDATE marketing_cities SET population = 6485 WHERE name = 'Rzepin';
UPDATE marketing_cities SET population = 6474 WHERE name = 'Otmuchów';
UPDATE marketing_cities SET population = 6444 WHERE name = 'Żmigród';
UPDATE marketing_cities SET population = 6437 WHERE name = 'Koźmin Wielkopolski';
UPDATE marketing_cities SET population = 6425 WHERE name = 'Dobczyce';
UPDATE marketing_cities SET population = 6399 WHERE name = 'Bełżyce';
UPDATE marketing_cities SET population = 6374 WHERE name = 'Opatów';
UPDATE marketing_cities SET population = 6364 WHERE name = 'Piława Górna';
UPDATE marketing_cities SET population = 6359 WHERE name = 'Sędziszów';
UPDATE marketing_cities SET population = 6355 WHERE name = 'Kłodawa';
UPDATE marketing_cities SET population = 6290 WHERE name = 'Mszczonów';
UPDATE marketing_cities SET population = 6246 WHERE name = 'Głuszyca';
UPDATE marketing_cities SET population = 6228 WHERE name = 'Polanica-Zdrój';
UPDATE marketing_cities SET population = 6223 WHERE name = 'Niemodlin';
UPDATE marketing_cities SET population = 6147 WHERE name = 'Krzyż Wielkopolski';
UPDATE marketing_cities SET population = 6140 WHERE name = 'Boguchwała';
UPDATE marketing_cities SET population = 6130 WHERE name = 'Sulejów';
UPDATE marketing_cities SET population = 6082 WHERE name = 'Piechowice';
UPDATE marketing_cities SET population = 6079 WHERE name = 'Przemków';
UPDATE marketing_cities SET population = 6063 WHERE name = 'Dynów';
UPDATE marketing_cities SET population = 5986 WHERE name = 'Grybów';
UPDATE marketing_cities SET population = 5977 WHERE name = 'Proszowice';
UPDATE marketing_cities SET population = 5956 WHERE name = 'Sieraków';
UPDATE marketing_cities SET population = 5948 WHERE name = 'Buk';
UPDATE marketing_cities SET population = 5940 WHERE name = 'Lubawka';
UPDATE marketing_cities SET population = 5926 WHERE name = 'Choroszcz';
UPDATE marketing_cities SET population = 5903 WHERE name = 'Stęszew';
UPDATE marketing_cities SET population = 5900 WHERE name = 'Więcbork';
UPDATE marketing_cities SET population = 5874 WHERE name = 'Kietrz';
UPDATE marketing_cities SET population = 5862 WHERE name = 'Karlino';
UPDATE marketing_cities SET population = 5846 WHERE name = 'Koniecpol';
UPDATE marketing_cities SET population = 5830 WHERE name = 'Czarne';
UPDATE marketing_cities SET population = 5793 WHERE name = 'Piwniczna-Zdrój';
UPDATE marketing_cities SET population = 5787 WHERE name = 'Wołczyn';
UPDATE marketing_cities SET population = 5769 WHERE name = 'Maków Podhalański';
UPDATE marketing_cities SET population = 5769 WHERE name = 'Przysucha';
UPDATE marketing_cities SET population = 5767 WHERE name = 'Pieńsk';
UPDATE marketing_cities SET population = 5758 WHERE name = 'Wieleń';
UPDATE marketing_cities SET population = 5746 WHERE name = 'Działoszyn';
UPDATE marketing_cities SET population = 5740 WHERE name = 'Nowa Sarzyna';
UPDATE marketing_cities SET population = 5724 WHERE name = 'Nowe';
UPDATE marketing_cities SET population = 5711 WHERE name = 'Szczyrk';
UPDATE marketing_cities SET population = 5696 WHERE name = 'Lewin Brzeski';
UPDATE marketing_cities SET population = 5658 WHERE name = 'Jedlicze';
UPDATE marketing_cities SET population = 5655 WHERE name = 'Szczawnica';
UPDATE marketing_cities SET population = 5624 WHERE name = 'Pakość';
UPDATE marketing_cities SET population = 5621 WHERE name = 'Śmigiel';
UPDATE marketing_cities SET population = 5616 WHERE name = 'Stronie Śląskie';
UPDATE marketing_cities SET population = 5589 WHERE name = 'Strzelno';
UPDATE marketing_cities SET population = 5569 WHERE name = 'Stąporków';
UPDATE marketing_cities SET population = 5563 WHERE name = 'Głogówek';
UPDATE marketing_cities SET population = 5544 WHERE name = 'Siewierz';
UPDATE marketing_cities SET population = 5534 WHERE name = 'Szczawno-Zdrój';
UPDATE marketing_cities SET population = 5529 WHERE name = 'Susz';
UPDATE marketing_cities SET population = 5526 WHERE name = 'Orzysz';
UPDATE marketing_cities SET population = 5526 WHERE name = 'Ścinawa';
UPDATE marketing_cities SET population = 5499 WHERE name = 'Radziejów';
UPDATE marketing_cities SET population = 5466 WHERE name = 'Lądek-Zdrój';
UPDATE marketing_cities SET population = 5457 WHERE name = 'Terespol';
UPDATE marketing_cities SET population = 5429 WHERE name = 'Kazimierza Wielka';
UPDATE marketing_cities SET population = 5406 WHERE name = 'Lesko';
UPDATE marketing_cities SET population = 5402 WHERE name = 'Dąbrowa Białostocka';
UPDATE marketing_cities SET population = 5377 WHERE name = 'Lipsko';
UPDATE marketing_cities SET population = 5320 WHERE name = 'Dzierzgoń';
UPDATE marketing_cities SET population = 5307 WHERE name = 'Międzyzdroje';
UPDATE marketing_cities SET population = 5230 WHERE name = 'Kuźnia Raciborska';
UPDATE marketing_cities SET population = 5221 WHERE name = 'Brusy';
UPDATE marketing_cities SET population = 5214 WHERE name = 'Radymno';
UPDATE marketing_cities SET population = 5159 WHERE name = 'Sejny';
UPDATE marketing_cities SET population = 5152 WHERE name = 'Jordanów';
UPDATE marketing_cities SET population = 5131 WHERE name = 'Wyrzysk';
UPDATE marketing_cities SET population = 5118 WHERE name = 'Jaworzyna Śląska';
UPDATE marketing_cities SET population = 5114 WHERE name = 'Odolanów';
UPDATE marketing_cities SET population = 5093 WHERE name = 'Zagórz';
UPDATE marketing_cities SET population = 5060 WHERE name = 'Nowogród Bobrzański';
UPDATE marketing_cities SET population = 5052 WHERE name = 'Borne Sulinowo';
UPDATE marketing_cities SET population = 5044 WHERE name = 'Szczytna';
UPDATE marketing_cities SET population = 5020 WHERE name = 'Debrzno';
UPDATE marketing_cities SET population = 4997 WHERE name = 'Zbąszynek';
UPDATE marketing_cities SET population = 4962 WHERE name = 'Szczebrzeszyn';
UPDATE marketing_cities SET population = 4958 WHERE name = 'Pilzno';
UPDATE marketing_cities SET population = 4932 WHERE name = 'Czempiń';
UPDATE marketing_cities SET population = 4913 WHERE name = 'Bolków';
UPDATE marketing_cities SET population = 4834 WHERE name = 'Małkinia Górna';
UPDATE marketing_cities SET population = 4814 WHERE name = 'Bychawa';
UPDATE marketing_cities SET population = 4809 WHERE name = 'Bierutów';
UPDATE marketing_cities SET population = 4809 WHERE name = 'Łaskarzew';
UPDATE marketing_cities SET population = 4789 WHERE name = 'Jedlina-Zdrój';
UPDATE marketing_cities SET population = 4744 WHERE name = 'Nowe Skalmierzyce';
UPDATE marketing_cities SET population = 4739 WHERE name = 'Wolin';
UPDATE marketing_cities SET population = 4737 WHERE name = 'Muszyna';
UPDATE marketing_cities SET population = 4658 WHERE name = 'Serock';
UPDATE marketing_cities SET population = 4642 WHERE name = 'Iłża';
UPDATE marketing_cities SET population = 4634 WHERE name = 'Kobylnica';
UPDATE marketing_cities SET population = 4587 WHERE name = 'Ciechanowiec';
UPDATE marketing_cities SET population = 4582 WHERE name = 'Supraśl';
UPDATE marketing_cities SET population = 4564 WHERE name = 'Pilawa';
UPDATE marketing_cities SET population = 4563 WHERE name = 'Brześć Kujawski';
UPDATE marketing_cities SET population = 4549 WHERE name = 'Biecz';
UPDATE marketing_cities SET population = 4538 WHERE name = 'Żarki';
UPDATE marketing_cities SET population = 4535 WHERE name = 'Reszel';
UPDATE marketing_cities SET population = 4515 WHERE name = 'Kcynia';
UPDATE marketing_cities SET population = 4501 WHERE name = 'Łabiszyn';
UPDATE marketing_cities SET population = 4487 WHERE name = 'Karpacz';
UPDATE marketing_cities SET population = 4475 WHERE name = 'Budzyń';
UPDATE marketing_cities SET population = 4469 WHERE name = 'Kalwaria Zebrzydowska';
UPDATE marketing_cities SET population = 4467 WHERE name = 'Kamieniec Ząbkowicki';
UPDATE marketing_cities SET population = 4462 WHERE name = 'Skoki';
UPDATE marketing_cities SET population = 4451 WHERE name = 'Ożarów';
UPDATE marketing_cities SET population = 4450 WHERE name = 'Golina';
UPDATE marketing_cities SET population = 4445 WHERE name = 'Zduny';
UPDATE marketing_cities SET population = 4434 WHERE name = 'Ruciane-Nida';
UPDATE marketing_cities SET population = 4422 WHERE name = 'Duszniki-Zdrój';
UPDATE marketing_cities SET population = 4394 WHERE name = 'Chęciny';
UPDATE marketing_cities SET population = 4392 WHERE name = 'Piotrków Kujawski';
UPDATE marketing_cities SET population = 4391 WHERE name = 'Leśna';
UPDATE marketing_cities SET population = 4390 WHERE name = 'Raciąż';
UPDATE marketing_cities SET population = 4363 WHERE name = 'Kalisz Pomorski';
UPDATE marketing_cities SET population = 4361 WHERE name = 'Krzepice';
UPDATE marketing_cities SET population = 4338 WHERE name = 'Krobia';
UPDATE marketing_cities SET population = 4328 WHERE name = 'Rejowiec Fabryczny';
UPDATE marketing_cities SET population = 4325 WHERE name = 'Olszyna';
UPDATE marketing_cities SET population = 4310 WHERE name = 'Skaryszew';
UPDATE marketing_cities SET population = 4298 WHERE name = 'Mrocza';
UPDATE marketing_cities SET population = 4298 WHERE name = 'Woźniki';
UPDATE marketing_cities SET population = 4293 WHERE name = 'Słomniki';
UPDATE marketing_cities SET population = 4268 WHERE name = 'Sława';
UPDATE marketing_cities SET population = 4263 WHERE name = 'Nowogrodziec';
UPDATE marketing_cities SET population = 4258 WHERE name = 'Krośniewice';
UPDATE marketing_cities SET population = 4244 WHERE name = 'Bytom Odrzański';
UPDATE marketing_cities SET population = 4243 WHERE name = 'Ogrodzieniec';
UPDATE marketing_cities SET population = 4226 WHERE name = 'Nowy Staw';
UPDATE marketing_cities SET population = 4215 WHERE name = 'Jasień';
UPDATE marketing_cities SET population = 4210 WHERE name = 'Sokołów Małopolski';
UPDATE marketing_cities SET population = 4192 WHERE name = 'Szamocin';
UPDATE marketing_cities SET population = 4184 WHERE name = 'Żabno';
UPDATE marketing_cities SET population = 4154 WHERE name = 'Szczucin';
UPDATE marketing_cities SET population = 4150 WHERE name = 'Tarczyn';
UPDATE marketing_cities SET population = 4147 WHERE name = 'Resko';
UPDATE marketing_cities SET population = 4145 WHERE name = 'Korsze';
UPDATE marketing_cities SET population = 4132 WHERE name = 'Zawidów';
UPDATE marketing_cities SET population = 4102 WHERE name = 'Kowalewo Pomorskie';
UPDATE marketing_cities SET population = 4097 WHERE name = 'Kleczew';
UPDATE marketing_cities SET population = 4082 WHERE name = 'Gąbin';
UPDATE marketing_cities SET population = 4047 WHERE name = 'Biała Piska';
UPDATE marketing_cities SET population = 4026 WHERE name = 'Tułowice';
UPDATE marketing_cities SET population = 3995 WHERE name = 'Świeradów-Zdrój';
UPDATE marketing_cities SET population = 3983 WHERE name = 'Tyczyn';
UPDATE marketing_cities SET population = 3976 WHERE name = 'Jedlnia-Letnisko';
UPDATE marketing_cities SET population = 3964 WHERE name = 'Mieroszów';
UPDATE marketing_cities SET population = 3957 WHERE name = 'Bobolice';
UPDATE marketing_cities SET population = 3947 WHERE name = 'Czerwieńsk';
UPDATE marketing_cities SET population = 3901 WHERE name = 'Babimost';
UPDATE marketing_cities SET population = 3900 WHERE name = 'Płoty';
UPDATE marketing_cities SET population = 3897 WHERE name = 'Janowiec Wielkopolski';
UPDATE marketing_cities SET population = 3896 WHERE name = 'Ośno Lubuskie';
UPDATE marketing_cities SET population = 3895 WHERE name = 'Żelechów';
UPDATE marketing_cities SET population = 3887 WHERE name = 'Górowo Iławeckie';
UPDATE marketing_cities SET population = 3887 WHERE name = 'Lipiany';
UPDATE marketing_cities SET population = 3851 WHERE name = 'Nekla';
UPDATE marketing_cities SET population = 3844 WHERE name = 'Iłowa';
UPDATE marketing_cities SET population = 3842 WHERE name = 'Okonek';
UPDATE marketing_cities SET population = 3803 WHERE name = 'Drzewica';
UPDATE marketing_cities SET population = 3801 WHERE name = 'Podkowa Leśna';
UPDATE marketing_cities SET population = 3786 WHERE name = 'Mirsk';
UPDATE marketing_cities SET population = 3774 WHERE name = 'Kargowa';
UPDATE marketing_cities SET population = 3774 WHERE name = 'Rymanów';
UPDATE marketing_cities SET population = 3772 WHERE name = 'Czarny Dunajec';
UPDATE marketing_cities SET population = 3755 WHERE name = 'Skała';
UPDATE marketing_cities SET population = 3741 WHERE name = 'Mikołajki';
UPDATE marketing_cities SET population = 3740 WHERE name = 'Pruchnik';
UPDATE marketing_cities SET population = 3730 WHERE name = 'Jabłonowo Pomorskie';
UPDATE marketing_cities SET population = 3727 WHERE name = 'Nałęczów';
UPDATE marketing_cities SET population = 3714 WHERE name = 'Halinów';
UPDATE marketing_cities SET population = 3694 WHERE name = 'Brańsk';
UPDATE marketing_cities SET population = 3677 WHERE name = 'Barwice';
UPDATE marketing_cities SET population = 3672 WHERE name = 'Nowe Miasto nad Pilicą';
UPDATE marketing_cities SET population = 3670 WHERE name = 'Małogoszcz';
UPDATE marketing_cities SET population = 3665 WHERE name = 'Dobrodzień';
UPDATE marketing_cities SET population = 3659 WHERE name = 'Strumień';
UPDATE marketing_cities SET population = 3623 WHERE name = 'Ujście';
UPDATE marketing_cities SET population = 3619 WHERE name = 'Rakoniewice';
UPDATE marketing_cities SET population = 3616 WHERE name = 'Zator';
UPDATE marketing_cities SET population = 3611 WHERE name = 'Opatówek';
UPDATE marketing_cities SET population = 3603 WHERE name = 'Krajenka';
UPDATE marketing_cities SET population = 3603 WHERE name = 'Skórcz';
UPDATE marketing_cities SET population = 3596 WHERE name = 'Chmielnik';
UPDATE marketing_cities SET population = 3586 WHERE name = 'Mrozy';
UPDATE marketing_cities SET population = 3577 WHERE name = 'Mieszkowice';
UPDATE marketing_cities SET population = 3572 WHERE name = 'Wojcieszów';
UPDATE marketing_cities SET population = 3569 WHERE name = 'Toszek';
UPDATE marketing_cities SET population = 3558 WHERE name = 'Kępice';
UPDATE marketing_cities SET population = 3556 WHERE name = 'Prochowice';
UPDATE marketing_cities SET population = 3542 WHERE name = 'Skępe';
UPDATE marketing_cities SET population = 3541 WHERE name = 'Łeba';
UPDATE marketing_cities SET population = 3534 WHERE name = 'Miłosław';
UPDATE marketing_cities SET population = 3532 WHERE name = 'Byczyna';
UPDATE marketing_cities SET population = 3532 WHERE name = 'Szczekociny';
UPDATE marketing_cities SET population = 3496 WHERE name = 'Małomice';
UPDATE marketing_cities SET population = 3472 WHERE name = 'Sompolno';
UPDATE marketing_cities SET population = 3468 WHERE name = 'Kowal';
UPDATE marketing_cities SET population = 3458 WHERE name = 'Przedbórz';
UPDATE marketing_cities SET population = 3428 WHERE name = 'Stryków';
UPDATE marketing_cities SET population = 3397 WHERE name = 'Myszyniec';
UPDATE marketing_cities SET population = 3382 WHERE name = 'Rzgów';
UPDATE marketing_cities SET population = 3346 WHERE name = 'Maszewo';
UPDATE marketing_cities SET population = 3341 WHERE name = 'Szczuczyn';
UPDATE marketing_cities SET population = 3340 WHERE name = 'Złoczew';
UPDATE marketing_cities SET population = 3336 WHERE name = 'Alwernia';
UPDATE marketing_cities SET population = 3310 WHERE name = 'Wojnicz';
UPDATE marketing_cities SET population = 3304 WHERE name = 'Tarnogród';
UPDATE marketing_cities SET population = 3296 WHERE name = 'Kolonowskie';
UPDATE marketing_cities SET population = 3238 WHERE name = 'Kock';
UPDATE marketing_cities SET population = 3225 WHERE name = 'Radomyśl Wielki';
UPDATE marketing_cities SET population = 3222 WHERE name = 'Kobylin';
UPDATE marketing_cities SET population = 3212 WHERE name = 'Hel';
UPDATE marketing_cities SET population = 3208 WHERE name = 'Warta';
UPDATE marketing_cities SET population = 3204 WHERE name = 'Tuliszków';
UPDATE marketing_cities SET population = 3203 WHERE name = 'Miejska Górka';
UPDATE marketing_cities SET population = 3167 WHERE name = 'Piekoszów';
UPDATE marketing_cities SET population = 3161 WHERE name = 'Łasin';
UPDATE marketing_cities SET population = 3158 WHERE name = 'Gołańcz';
UPDATE marketing_cities SET population = 3149 WHERE name = 'Zakroczym';
UPDATE marketing_cities SET population = 3142 WHERE name = 'Wilamowice';
UPDATE marketing_cities SET population = 3137 WHERE name = 'Bobowa';
UPDATE marketing_cities SET population = 3135 WHERE name = 'Jeziorany';
UPDATE marketing_cities SET population = 3132 WHERE name = 'Biała Rawska';
UPDATE marketing_cities SET population = 3131 WHERE name = 'Kańczuga';
UPDATE marketing_cities SET population = 3124 WHERE name = 'Ślesin';
UPDATE marketing_cities SET population = 3123 WHERE name = 'Chociwel';
UPDATE marketing_cities SET population = 3112 WHERE name = 'Dobrzyca';
UPDATE marketing_cities SET population = 3101 WHERE name = 'Zwierzyniec';
UPDATE marketing_cities SET population = 3100 WHERE name = 'Chorzele';
UPDATE marketing_cities SET population = 3095 WHERE name = 'Radoszyce';
UPDATE marketing_cities SET population = 3092 WHERE name = 'Pyzdry';
UPDATE marketing_cities SET population = 3074 WHERE name = 'Krasnobród';
UPDATE marketing_cities SET population = 3054 WHERE name = 'Mirosławiec';
UPDATE marketing_cities SET population = 3017 WHERE name = 'Dobiegniew';
UPDATE marketing_cities SET population = 2984 WHERE name = 'Ćmielów';
UPDATE marketing_cities SET population = 2984 WHERE name = 'Margonin';
UPDATE marketing_cities SET population = 2983 WHERE name = 'Michałowo';
UPDATE marketing_cities SET population = 2981 WHERE name = 'Wielbark';
UPDATE marketing_cities SET population = 2977 WHERE name = 'Gozdnica';
UPDATE marketing_cities SET population = 2976 WHERE name = 'Glinojeck';
UPDATE marketing_cities SET population = 2957 WHERE name = 'Uniejów';
UPDATE marketing_cities SET population = 2954 WHERE name = 'Zaklików';
UPDATE marketing_cities SET population = 2948 WHERE name = 'Oleszyce';
UPDATE marketing_cities SET population = 2939 WHERE name = 'Łobżenica';
UPDATE marketing_cities SET population = 2933 WHERE name = 'Lwówek';
UPDATE marketing_cities SET population = 2932 WHERE name = 'Niemcza';
UPDATE marketing_cities SET population = 2927 WHERE name = 'Lubraniec';
UPDATE marketing_cities SET population = 2919 WHERE name = 'Rydzyna';
UPDATE marketing_cities SET population = 2915 WHERE name = 'Bojanowo';
UPDATE marketing_cities SET population = 2904 WHERE name = 'Kaczory';
UPDATE marketing_cities SET population = 2902 WHERE name = 'Zagórów';
UPDATE marketing_cities SET population = 2898 WHERE name = 'Mielno';
UPDATE marketing_cities SET population = 2883 WHERE name = 'Kunów';
UPDATE marketing_cities SET population = 2881 WHERE name = 'Polanów';
UPDATE marketing_cities SET population = 2878 WHERE name = 'Poniec';
UPDATE marketing_cities SET population = 2873 WHERE name = 'Recz';
UPDATE marketing_cities SET population = 2862 WHERE name = 'Kałuszyn';
UPDATE marketing_cities SET population = 2861 WHERE name = 'Baborów';
UPDATE marketing_cities SET population = 2856 WHERE name = 'Daleszyce';
UPDATE marketing_cities SET population = 2831 WHERE name = 'Sulmierzyce';
UPDATE marketing_cities SET population = 2830 WHERE name = 'Ryglice';
UPDATE marketing_cities SET population = 2827 WHERE name = 'Ryn';
UPDATE marketing_cities SET population = 2825 WHERE name = 'Piszczac';
UPDATE marketing_cities SET population = 2821 WHERE name = 'Drobin';
UPDATE marketing_cities SET population = 2802 WHERE name = 'Węgliniec';
UPDATE marketing_cities SET population = 2771 WHERE name = 'Węgorzyno';
UPDATE marketing_cities SET population = 2768 WHERE name = 'Cybinka';
UPDATE marketing_cities SET population = 2763 WHERE name = 'Czarna Woda';
UPDATE marketing_cities SET population = 2763 WHERE name = 'Nowy Wiśnicz';
UPDATE marketing_cities SET population = 2757 WHERE name = 'Radłów';
UPDATE marketing_cities SET population = 2749 WHERE name = 'Brzostek';
UPDATE marketing_cities SET population = 2726 WHERE name = 'Knyszyn';
UPDATE marketing_cities SET population = 2724 WHERE name = 'Nowe Miasteczko';
UPDATE marketing_cities SET population = 2724 WHERE name = 'Wąchock';
UPDATE marketing_cities SET population = 2718 WHERE name = 'Książ Wielkopolski';
UPDATE marketing_cities SET population = 2710 WHERE name = 'Pruszcz';
UPDATE marketing_cities SET population = 2703 WHERE name = 'Kamieńsk';
UPDATE marketing_cities SET population = 2698 WHERE name = 'Różan';
UPDATE marketing_cities SET population = 2696 WHERE name = 'Złoty Stok';
UPDATE marketing_cities SET population = 2679 WHERE name = 'Jastarnia';
UPDATE marketing_cities SET population = 2679 WHERE name = 'Pieniężno';
UPDATE marketing_cities SET population = 2673 WHERE name = 'Golczewo';
UPDATE marketing_cities SET population = 2671 WHERE name = 'Czerniejewo';
UPDATE marketing_cities SET population = 2659 WHERE name = 'Janów Podlaski';
UPDATE marketing_cities SET population = 2647 WHERE name = 'Dziwnów';
UPDATE marketing_cities SET population = 2647 WHERE name = 'Wąsosz';
UPDATE marketing_cities SET population = 2646 WHERE name = 'Czyżew';
UPDATE marketing_cities SET population = 2644 WHERE name = 'Tolkmicko';
UPDATE marketing_cities SET population = 2617 WHERE name = 'Kurów';
UPDATE marketing_cities SET population = 2614 WHERE name = 'Wysoka';
UPDATE marketing_cities SET population = 2605 WHERE name = 'Kłecko';
UPDATE marketing_cities SET population = 2595 WHERE name = 'Pełczyce';
UPDATE marketing_cities SET population = 2594 WHERE name = 'Izbica Kujawska';
UPDATE marketing_cities SET population = 2573 WHERE name = 'Zaniemyśl';
UPDATE marketing_cities SET population = 2569 WHERE name = 'Wyszogród';
UPDATE marketing_cities SET population = 2564 WHERE name = 'Leśnica';
UPDATE marketing_cities SET population = 2561 WHERE name = 'Prószków';
UPDATE marketing_cities SET population = 2540 WHERE name = 'Miłakowo';
UPDATE marketing_cities SET population = 2534 WHERE name = 'Kazimierz Dolny';
UPDATE marketing_cities SET population = 2531 WHERE name = 'Piaski';
UPDATE marketing_cities SET population = 2520 WHERE name = 'Torzym';
UPDATE marketing_cities SET population = 2514 WHERE name = 'Międzylesie';
UPDATE marketing_cities SET population = 2500 WHERE name = 'Borek Wielkopolski';
UPDATE marketing_cities SET population = 2498 WHERE name = 'Pasym';
UPDATE marketing_cities SET population = 2497 WHERE name = 'Bardo';
UPDATE marketing_cities SET population = 2490 WHERE name = 'Zabłudów';
UPDATE marketing_cities SET population = 2485 WHERE name = 'Tychowo';
UPDATE marketing_cities SET population = 2480 WHERE name = 'Stoczek Łukowski';
UPDATE marketing_cities SET population = 2464 WHERE name = 'Stepnica';
UPDATE marketing_cities SET population = 2447 WHERE name = 'Ciężkowice';
UPDATE marketing_cities SET population = 2441 WHERE name = 'Świątniki Górne';
UPDATE marketing_cities SET population = 2439 WHERE name = 'Gorzów Śląski';
UPDATE marketing_cities SET population = 2439 WHERE name = 'Gościno';
UPDATE marketing_cities SET population = 2438 WHERE name = 'Koziegłowy';
UPDATE marketing_cities SET population = 2436 WHERE name = 'Annopol';
UPDATE marketing_cities SET population = 2431 WHERE name = 'Koprzywnica';
UPDATE marketing_cities SET population = 2424 WHERE name = 'Lubycza Królewska';
UPDATE marketing_cities SET population = 2421 WHERE name = 'Miłomłyn';
UPDATE marketing_cities SET population = 2401 WHERE name = 'Radków';
UPDATE marketing_cities SET population = 2396 WHERE name = 'Łęknica';
UPDATE marketing_cities SET population = 2392 WHERE name = 'Osieczna';
UPDATE marketing_cities SET population = 2390 WHERE name = 'Biała';
UPDATE marketing_cities SET population = 2385 WHERE name = 'Obrzycko';
UPDATE marketing_cities SET population = 2362 WHERE name = 'Mieścisko';
UPDATE marketing_cities SET population = 2353 WHERE name = 'Rychwał';
UPDATE marketing_cities SET population = 2341 WHERE name = 'Międzybórz';
UPDATE marketing_cities SET population = 2339 WHERE name = 'Trzciel';
UPDATE marketing_cities SET population = 2335 WHERE name = 'Kamień Krajeński';
UPDATE marketing_cities SET population = 2328 WHERE name = 'Bisztynek';
UPDATE marketing_cities SET population = 2323 WHERE name = 'Czchów';
UPDATE marketing_cities SET population = 2313 WHERE name = 'Krynki';
UPDATE marketing_cities SET population = 2309 WHERE name = 'Siennica';
UPDATE marketing_cities SET population = 2308 WHERE name = 'Człopa';
UPDATE marketing_cities SET population = 2305 WHERE name = 'Frombork';
UPDATE marketing_cities SET population = 2301 WHERE name = 'Wolbórz';
UPDATE marketing_cities SET population = 2296 WHERE name = 'Dobra';
UPDATE marketing_cities SET population = 2279 WHERE name = 'Cegłów';
UPDATE marketing_cities SET population = 2279 WHERE name = 'Chodecz';
UPDATE marketing_cities SET population = 2250 WHERE name = 'Drawno';
UPDATE marketing_cities SET population = 2250 WHERE name = 'Lipsk';
UPDATE marketing_cities SET population = 2241 WHERE name = 'Lututów';
UPDATE marketing_cities SET population = 2234 WHERE name = 'Świerzawa';
UPDATE marketing_cities SET population = 2226 WHERE name = 'Prusice';
UPDATE marketing_cities SET population = 2218 WHERE name = 'Dobrzany';
UPDATE marketing_cities SET population = 2208 WHERE name = 'Biały Bór';
UPDATE marketing_cities SET population = 2200 WHERE name = 'Trzcińsko-Zdrój';
UPDATE marketing_cities SET population = 2198 WHERE name = 'Wiązów';
UPDATE marketing_cities SET population = 2193 WHERE name = 'Mogielnica';
UPDATE marketing_cities SET population = 2190 WHERE name = 'Bodzentyn';
UPDATE marketing_cities SET population = 2159 WHERE name = 'Stawiski';
UPDATE marketing_cities SET population = 2157 WHERE name = 'Szepietowo';
UPDATE marketing_cities SET population = 2154 WHERE name = 'Staroźreby';
UPDATE marketing_cities SET population = 2150 WHERE name = 'Nowogród';
UPDATE marketing_cities SET population = 2148 WHERE name = 'Błażowa';
UPDATE marketing_cities SET population = 2137 WHERE name = 'Suchowola';
UPDATE marketing_cities SET population = 2134 WHERE name = 'Krzanowice';
UPDATE marketing_cities SET population = 2132 WHERE name = 'Sieniawa';
UPDATE marketing_cities SET population = 2129 WHERE name = 'Zalewo';
UPDATE marketing_cities SET population = 2119 WHERE name = 'Raszków';
UPDATE marketing_cities SET population = 2111 WHERE name = 'Łaszczów';
UPDATE marketing_cities SET population = 2109 WHERE name = 'Żerków';
UPDATE marketing_cities SET population = 2089 WHERE name = 'Ostrów Lubelski';
UPDATE marketing_cities SET population = 2087 WHERE name = 'Pogorzela';
UPDATE marketing_cities SET population = 2081 WHERE name = 'Kisielice';
UPDATE marketing_cities SET population = 2080 WHERE name = 'Lubniewice';
UPDATE marketing_cities SET population = 2078 WHERE name = 'Miękinia';
UPDATE marketing_cities SET population = 2072 WHERE name = 'Dobrzyń nad Wisłą';
UPDATE marketing_cities SET population = 2071 WHERE name = 'Kosów Lacki';
UPDATE marketing_cities SET population = 2054 WHERE name = 'Tyszowce';
UPDATE marketing_cities SET population = 2047 WHERE name = 'Błaszki';
UPDATE marketing_cities SET population = 2044 WHERE name = 'Dukla';
UPDATE marketing_cities SET population = 2040 WHERE name = 'Narol';
UPDATE marketing_cities SET population = 2026 WHERE name = 'Rejowiec';
UPDATE marketing_cities SET population = 2020 WHERE name = 'Końskowola';
UPDATE marketing_cities SET population = 1996 WHERE name = 'Branice';
UPDATE marketing_cities SET population = 1994 WHERE name = 'Kikół';
UPDATE marketing_cities SET population = 1987 WHERE name = 'Lubomierz';
UPDATE marketing_cities SET population = 1982 WHERE name = 'Dąbie';
UPDATE marketing_cities SET population = 1970 WHERE name = 'Osiek';
UPDATE marketing_cities SET population = 1966 WHERE name = 'Jutrosin';
UPDATE marketing_cities SET population = 1966 WHERE name = 'Tykocin';
UPDATE marketing_cities SET population = 1938 WHERE name = 'Koźminek';
UPDATE marketing_cities SET population = 1932 WHERE name = 'Drohiczyn';
UPDATE marketing_cities SET population = 1932 WHERE name = 'Sanniki';
UPDATE marketing_cities SET population = 1927 WHERE name = 'Sośnicowice';
UPDATE marketing_cities SET population = 1922 WHERE name = 'Cieszanów';
UPDATE marketing_cities SET population = 1919 WHERE name = 'Tuczno';
UPDATE marketing_cities SET population = 1917 WHERE name = 'Pilica';
UPDATE marketing_cities SET population = 1916 WHERE name = 'Ostroróg';
UPDATE marketing_cities SET population = 1912 WHERE name = 'Grabów nad Prosną';
UPDATE marketing_cities SET population = 1904 WHERE name = 'Brok';
UPDATE marketing_cities SET population = 1900 WHERE name = 'Sochocin';
UPDATE marketing_cities SET population = 1898 WHERE name = 'Szadek';
UPDATE marketing_cities SET population = 1892 WHERE name = 'Ińsko';
UPDATE marketing_cities SET population = 1884 WHERE name = 'Klimontów';
UPDATE marketing_cities SET population = 1883 WHERE name = 'Sępopol';
UPDATE marketing_cities SET population = 1834 WHERE name = 'Nieszawa';
UPDATE marketing_cities SET population = 1829 WHERE name = 'Bieżuń';
UPDATE marketing_cities SET population = 1826 WHERE name = 'Dobre';
UPDATE marketing_cities SET population = 1819 WHERE name = 'Goniądz';
UPDATE marketing_cities SET population = 1812 WHERE name = 'Mikstat';
UPDATE marketing_cities SET population = 1788 WHERE name = 'Przecław';
UPDATE marketing_cities SET population = 1784 WHERE name = 'Radzyń Chełmiński';
UPDATE marketing_cities SET population = 1774 WHERE name = 'Wielichowo';
UPDATE marketing_cities SET population = 1771 WHERE name = 'Korfantów';
UPDATE marketing_cities SET population = 1770 WHERE name = 'Stanisławów';
UPDATE marketing_cities SET population = 1769 WHERE name = 'Chocz';
UPDATE marketing_cities SET population = 1763 WHERE name = 'Młynary';
UPDATE marketing_cities SET population = 1742 WHERE name = 'Iwonicz-Zdrój';
UPDATE marketing_cities SET population = 1739 WHERE name = 'Izbica';
UPDATE marketing_cities SET population = 1734 WHERE name = 'Ujazd';
UPDATE marketing_cities SET population = 1725 WHERE name = 'Wleń';
UPDATE marketing_cities SET population = 1721 WHERE name = 'Krzywiń';
UPDATE marketing_cities SET population = 1713 WHERE name = 'Zawichost';
UPDATE marketing_cities SET population = 1712 WHERE name = 'Kamionka';
UPDATE marketing_cities SET population = 1710 WHERE name = 'Mordy';
UPDATE marketing_cities SET population = 1708 WHERE name = 'Morawica';
UPDATE marketing_cities SET population = 1690 WHERE name = 'Piątek';
UPDATE marketing_cities SET population = 1689 WHERE name = 'Rozprza';
UPDATE marketing_cities SET population = 1679 WHERE name = 'Urzędów';
UPDATE marketing_cities SET population = 1654 WHERE name = 'Nowe Brzesko';
UPDATE marketing_cities SET population = 1645 WHERE name = 'Lubowidz';
UPDATE marketing_cities SET population = 1641 WHERE name = 'Otyń';
UPDATE marketing_cities SET population = 1628 WHERE name = 'Zakliczyn';
UPDATE marketing_cities SET population = 1621 WHERE name = 'Przedecz';
UPDATE marketing_cities SET population = 1612 WHERE name = 'Moryń';
UPDATE marketing_cities SET population = 1607 WHERE name = 'Jedwabne';
UPDATE marketing_cities SET population = 1569 WHERE name = 'Lutomiersk';
UPDATE marketing_cities SET population = 1553 WHERE name = 'Dolsk';
UPDATE marketing_cities SET population = 1543 WHERE name = 'Łagów';
UPDATE marketing_cities SET population = 1539 WHERE name = 'Rajgród';
UPDATE marketing_cities SET population = 1539 WHERE name = 'Strzeleczki';
UPDATE marketing_cities SET population = 1530 WHERE name = 'Nowe Miasto';
UPDATE marketing_cities SET population = 1497 WHERE name = 'Cedynia';
UPDATE marketing_cities SET population = 1461 WHERE name = 'Stawiszyn';
UPDATE marketing_cities SET population = 1459 WHERE name = 'Modliborzyce';
UPDATE marketing_cities SET population = 1440 WHERE name = 'Suchań';
UPDATE marketing_cities SET population = 1432 WHERE name = 'Frampol';
UPDATE marketing_cities SET population = 1430 WHERE name = 'Baranów Sandomierski';
UPDATE marketing_cities SET population = 1427 WHERE name = 'Kołaczyce';
UPDATE marketing_cities SET population = 1427 WHERE name = 'Ulanów';
UPDATE marketing_cities SET population = 1414 WHERE name = 'Stopnica';
UPDATE marketing_cities SET population = 1410 WHERE name = 'Maciejowice';
UPDATE marketing_cities SET population = 1406 WHERE name = 'Gąsawa';
UPDATE marketing_cities SET population = 1406 WHERE name = 'Siedliszcze';
UPDATE marketing_cities SET population = 1403 WHERE name = 'Górzno';
UPDATE marketing_cities SET population = 1403 WHERE name = 'Jaraczewo';
UPDATE marketing_cities SET population = 1402 WHERE name = 'Łopuszno';
UPDATE marketing_cities SET population = 1380 WHERE name = 'Latowicz';
UPDATE marketing_cities SET population = 1377 WHERE name = 'Lubień Kujawski';
UPDATE marketing_cities SET population = 1356 WHERE name = 'Nowa Słupia';
UPDATE marketing_cities SET population = 1350 WHERE name = 'Osjaków';
UPDATE marketing_cities SET population = 1347 WHERE name = 'Rychtal';
UPDATE marketing_cities SET population = 1347 WHERE name = 'Wiskitki';
UPDATE marketing_cities SET population = 1343 WHERE name = 'Gowarczów';
UPDATE marketing_cities SET population = 1322 WHERE name = 'Iwaniska';
UPDATE marketing_cities SET population = 1307 WHERE name = 'Czemierniki';
UPDATE marketing_cities SET population = 1290 WHERE name = 'Krynica Morska';
UPDATE marketing_cities SET population = 1278 WHERE name = 'Jeżów';
UPDATE marketing_cities SET population = 1266 WHERE name = 'Szlichtyngowa';
UPDATE marketing_cities SET population = 1263 WHERE name = 'Skalbmierz';
UPDATE marketing_cities SET population = 1216 WHERE name = 'Kleszczele';
UPDATE marketing_cities SET population = 1190 WHERE name = 'Jawornik Polski';
UPDATE marketing_cities SET population = 1178 WHERE name = 'Nowe Warpno';
UPDATE marketing_cities SET population = 1160 WHERE name = 'Pierzchnica';
UPDATE marketing_cities SET population = 1144 WHERE name = 'Przyrów';
UPDATE marketing_cities SET population = 1135 WHERE name = 'Bodzanów';
UPDATE marketing_cities SET population = 1132 WHERE name = 'Pacanów';
UPDATE marketing_cities SET population = 1124 WHERE name = 'Włodowice';
UPDATE marketing_cities SET population = 1104 WHERE name = 'Bobrowniki';
UPDATE marketing_cities SET population = 1099 WHERE name = 'Osieck';
UPDATE marketing_cities SET population = 1095 WHERE name = 'Szydłów';
UPDATE marketing_cities SET population = 1093 WHERE name = 'Bogoria';
UPDATE marketing_cities SET population = 1082 WHERE name = 'Wodzisław';
UPDATE marketing_cities SET population = 1080 WHERE name = 'Miasteczko Krajeńskie';
UPDATE marketing_cities SET population = 1074 WHERE name = 'Żarnów';
UPDATE marketing_cities SET population = 1071 WHERE name = 'Jastrząb';
UPDATE marketing_cities SET population = 1068 WHERE name = 'Białaczów';
UPDATE marketing_cities SET population = 1010 WHERE name = 'Czerwińsk nad Wisłą';
UPDATE marketing_cities SET population = 1003 WHERE name = 'Grabów';
UPDATE marketing_cities SET population = 1000 WHERE name = 'Janów';
UPDATE marketing_cities SET population = 997 WHERE name = 'Sobków';
UPDATE marketing_cities SET population = 987 WHERE name = 'Bircza';
UPDATE marketing_cities SET population = 983 WHERE name = 'Suraż';
UPDATE marketing_cities SET population = 975 WHERE name = 'Wąwolnica';
UPDATE marketing_cities SET population = 967 WHERE name = 'Odrzywół';
UPDATE marketing_cities SET population = 966 WHERE name = 'Magnuszew';
UPDATE marketing_cities SET population = 939 WHERE name = 'Solec nad Wisłą';
UPDATE marketing_cities SET population = 934 WHERE name = 'Jadów';
UPDATE marketing_cities SET population = 928 WHERE name = 'Sienno';
UPDATE marketing_cities SET population = 919 WHERE name = 'Parzęczew';
UPDATE marketing_cities SET population = 917 WHERE name = 'Goraj';
UPDATE marketing_cities SET population = 907 WHERE name = 'Przytyk';
UPDATE marketing_cities SET population = 904 WHERE name = 'Nowy Korczyn';
UPDATE marketing_cities SET population = 902 WHERE name = 'Działoszyce';
UPDATE marketing_cities SET population = 902 WHERE name = 'Józefów nad Wisłą';
UPDATE marketing_cities SET population = 899 WHERE name = 'Bolimów';
UPDATE marketing_cities SET population = 896 WHERE name = 'Wyśmierzyce';
UPDATE marketing_cities SET population = 889 WHERE name = 'Brody';
UPDATE marketing_cities SET population = 873 WHERE name = 'Turobin';
UPDATE marketing_cities SET population = 866 WHERE name = 'Dubiecko';
UPDATE marketing_cities SET population = 847 WHERE name = 'Dąbrowice';
UPDATE marketing_cities SET population = 831 WHERE name = 'Kiernozia';
UPDATE marketing_cities SET population = 829 WHERE name = 'Inowłódz';
UPDATE marketing_cities SET population = 825 WHERE name = 'Głowaczów';
UPDATE marketing_cities SET population = 817 WHERE name = 'Książ Wielki';
UPDATE marketing_cities SET population = 779 WHERE name = 'Gielniów';
UPDATE marketing_cities SET population = 775 WHERE name = 'Koszyce';
UPDATE marketing_cities SET population = 738 WHERE name = 'Ciepielów';
UPDATE marketing_cities SET population = 506 WHERE name = 'Wiślica';
