-- Population from Wikipedia for cities in marketing_cities table

UPDATE marketing_cities SET population = 1794166 WHERE name = 'Warszawa';
UPDATE marketing_cities SET population = 779966 WHERE name = 'Kraków';
UPDATE marketing_cities SET population = 672185 WHERE name = 'Łódź';
UPDATE marketing_cities SET population = 641928 WHERE name = 'Wrocław';
UPDATE marketing_cities SET population = 532048 WHERE name = 'Poznań';
UPDATE marketing_cities SET population = 470805 WHERE name = 'Gdańsk';
UPDATE marketing_cities SET population = 398255 WHERE name = 'Szczecin';
UPDATE marketing_cities SET population = 344091 WHERE name = 'Bydgoszcz';
UPDATE marketing_cities SET population = 338586 WHERE name = 'Lublin';
UPDATE marketing_cities SET population = 296958 WHERE name = 'Białystok';
UPDATE marketing_cities SET population = 290553 WHERE name = 'Katowice';
UPDATE marketing_cities SET population = 244969 WHERE name = 'Gdynia';
UPDATE marketing_cities SET population = 217530 WHERE name = 'Częstochowa';
UPDATE marketing_cities SET population = 209296 WHERE name = 'Radom';
UPDATE marketing_cities SET population = 198613 WHERE name = 'Toruń';
UPDATE marketing_cities SET population = 197863 WHERE name = 'Rzeszów';
UPDATE marketing_cities SET population = 197586 WHERE name = 'Sosnowiec';
UPDATE marketing_cities SET population = 193415 WHERE name = 'Kielce';
UPDATE marketing_cities SET population = 177049 WHERE name = 'Gliwice';
UPDATE marketing_cities SET population = 171249 WHERE name = 'Olsztyn';
UPDATE marketing_cities SET population = 170924 WHERE name = 'Zabrze';
UPDATE marketing_cities SET population = 169756 WHERE name = 'Bielsko-Biała';
UPDATE marketing_cities SET population = 137128 WHERE name = 'Rybnik';
UPDATE marketing_cities SET population = 136423 WHERE name = 'Ruda Śląska';
UPDATE marketing_cities SET population = 127839 WHERE name = 'Opole';
UPDATE marketing_cities SET population = 126871 WHERE name = 'Tychy';
UPDATE marketing_cities SET population = 122589 WHERE name = 'Gorzów Wielkopolski';
UPDATE marketing_cities SET population = 118582 WHERE name = 'Elbląg';
UPDATE marketing_cities SET population = 118285 WHERE name = 'Dąbrowa Górnicza';
UPDATE marketing_cities SET population = 118268 WHERE name = 'Płock';
UPDATE marketing_cities SET population = 109971 WHERE name = 'Wałbrzych';
UPDATE marketing_cities SET population = 108561 WHERE name = 'Włocławek';
UPDATE marketing_cities SET population = 107498 WHERE name = 'Tarnów';
UPDATE marketing_cities SET population = 106846 WHERE name = 'Chorzów';
UPDATE marketing_cities SET population = 106235 WHERE name = 'Koszalin';
UPDATE marketing_cities SET population = 99106 WHERE name = 'Kalisz';
UPDATE marketing_cities SET population = 98436 WHERE name = 'Legnica';
UPDATE marketing_cities SET population = 93564 WHERE name = 'Grudziądz';
UPDATE marketing_cities SET population = 90368 WHERE name = 'Jaworzno';
UPDATE marketing_cities SET population = 88038 WHERE name = 'Jastrzębie-Zdrój';
UPDATE marketing_cities SET population = 83558 WHERE name = 'Nowy Sącz';
UPDATE marketing_cities SET population = 78335 WHERE name = 'Jelenia Góra';
UPDATE marketing_cities SET population = 77813 WHERE name = 'Siedlce';
UPDATE marketing_cities SET population = 74559 WHERE name = 'Mysłowice';
UPDATE marketing_cities SET population = 72527 WHERE name = 'Piła';
UPDATE marketing_cities SET population = 71710 WHERE name = 'Lubin';
UPDATE marketing_cities SET population = 71674 WHERE name = 'Inowrocław';
UPDATE marketing_cities SET population = 71560 WHERE name = 'Ostrów Wielkopolski';
UPDATE marketing_cities SET population = 67570 WHERE name = 'Gniezno';
UPDATE marketing_cities SET population = 67404 WHERE name = 'Ostrowiec Świętokrzyski';
